### ISSUE TITLE
Add atom-shell as runtime

### ISSUE THREAD

**Issue by suda** [mapbox/node-pre-gyp#110]
Atom Shell is a framework similar to node-webkit. It powers Atom editor from GitHub. With recent update to latest Chromium [broke node-pre-gyp modules install](https://github.com/atom/apm/issues/189). Suggested was that the best solution would be to add atom-shell as supported runtime (just like node-webkit). There is possible to [install native modules using node-gyp](https://github.com/atom/atom-shell/blob/master/docs/tutorial/using-native-node-modules.md) with latest version.

**Comment by choidamdam** [comment]
+1

**Comment by s-a** [comment]
:+1:

**Comment by s-a** [comment]
Any new s about this issue? @suda

**Comment by suda** [comment]
@s-a I'm still using @Mithgol's stale branch: https://github.com/Mithgol/node-pre-gyp/tree/support-atom-shell. I would love if this could be updated and merged in :)

**Comment by etiktin** [comment]
FYI, PR #175 adds basic support for Electron, so you can at least build the project locally.

**Comment by springmeyer** [comment]
Solved by https://github.com/mapbox/node-pre-gyp/pull/175 which has been merged and is included in the `v0.6.12` release of `node-pre-gyp`.
