### ISSUE TITLE
Cannot use example in the depot git

### ISSUE THREAD

**Issue by tounsi67** [mapbox/node-pre-gyp#129]
I build one example from the depot git, in Node : Depot/test/app1 

Like you can see it 
![buildtestapp1](https://cloud.githubusercontent.com/assets/9552805/5455181/9ade1c2a-8539-11e4-961c-1ab5ad8c01df.jpg)

But when I run it with NW, it crashed. 

![screenhunter_81 dec 16 15 39](https://cloud.githubusercontent.com/assets/9552805/5455199/bc091f6c-8539-11e4-88ed-524eb4435968.jpg)

index.js :
/********************************/
var binary = require('node-pre-gyp');
var path = require('path')
var binding_path = binary.find(path.resolve(path.join(__dirname,'./package.json')));
var binding = require(binding_path);

require('assert').equal(binding.hello(),"hello");
/******************************/

package.json
/********************************/
{
    "name": "node-pre-gyp-test-app1",
    "author": "Dane Springmeyer <springmeyer>",
    "description":"node-pre-gyp test",
    "repository"   :  {
       "type" : "git",
       "url"  : "git://github.com/mapbox/node-pre-gyp.git"
    },
    "version": "0.1.0",
    "main": "./index.js",
    "binary": {
        "module_name": "app1",
        "module_path": "./lib/binding/",
        "host":"https://node-pre-gyp-tests.s3-us-west-1.amazonaws.com"
    },
    "scripts": {
        "install":"node-pre-gyp install --fallback-to-build",
        "test":"node index.js"
    }
}

/********************************/

In the folder ./lib/binding/ I have a file app1.node. 

What I am missing ? 

Thank you in advance for your help. 

Windows 7 64 bit
NW 0.11.1

**Comment by springmeyer** [comment]
I recommend not using the `app1` test with node-webkit - it is only for testing node.js. Also don't use node-webkit 0.11.x - I would recommend sticking to 0.10.x as per https://github.com/mapbox/node-sqlite3/issues/404. And... if you are looking for a good app to test with node-webkit 0.10.x try node-sqlite3.
