### ISSUE TITLE
alternate aws

### ISSUE THREAD

**Issue by fengmk2** [mapbox/node-pre-gyp#138]
Now aws is the only options for store binary files.
I'm going to make it can configure by user.

e.g: I want to use `qiniu` (most popular in China) to store the binary files.

**Comment by springmeyer** [comment]
Any https based host is a valid place to store binary files. There is nothing requiring aws for users to install binaries via node-pre-gyp. The part that expects AWS is the `node-pre-gyp publish` command. But you can write your own publish script. Let me know what you think about https://github.com/mapbox/node-pre-gyp/issues/134#issuecomment-69281215.
