### ISSUE TITLE
Build on armv6l

### ISSUE THREAD

**Issue by timsuchanek** [mapbox/node-pre-gyp#155]
I'm trying to build node-pre-gyp on the Raspberry Pi 1 (armv6l arch).

But the following error occures:
https://gist.github.com/timsuchanek/d0613bcf91607d9c8b0a

npm-debug.log:
https://gist.github.com/timsuchanek/800bcd22d4a72d237640

Thanks!

**Comment by springmeyer** [comment]
It looks like what is happening is that an armv6i binary is not available for https://github.com/js-platform/node-webrtc (no surprise) and the source compile fallback is failing. It is likely because you are missing depedencies of https://github.com/js-platform/node-webrtc.

**Comment by springmeyer** [comment]
closing as this is an issue with https://github.com/js-platform/node-webrtc and node-pre-gyp.
