### ISSUE TITLE
On OSX numerous warnings give uncertainty about the status of the install

### ISSUE THREAD

**Issue by kdemarest** [mapbox/node-pre-gyp#164]
Apologies if this already exists among these issues - I searched and didn't see it.

When installing node-pre-gyp 0.6.4 with `npm install` on OSX 10.10.1 a number of bundled packages are not found:

npm WARN installMany nopt was bundled with node-pre-gyp@0.6.4, but bundled package wasn't found in unpacked tree
npm WARN installMany npmlog was bundled with node-pre-gyp@0.6.4, but bundled package wasn't found in unpacked tree
npm WARN installMany request was bundled with node-pre-gyp@0.6.4, but bundled package wasn't found in unpacked tree
npm WARN installMany semver was bundled with node-pre-gyp@0.6.4, but bundled package wasn't found in unpacked tree
npm WARN installMany tar was bundled with node-pre-gyp@0.6.4, but bundled package wasn't found in unpacked tree
npm WARN installMany tar-pack was bundled with node-pre-gyp@0.6.4, but bundled package wasn't found in unpacked tree
npm WARN installMany mkdirp was bundled with node-pre-gyp@0.6.4, but bundled package wasn't found in unpacked tree
npm WARN installMany rc was bundled with node-pre-gyp@0.6.4, but bundled package wasn't found in unpacked tree
npm WARN installMany rimraf was bundled with node-pre-gyp@0.6.4, but bundled package wasn't found in unpacked tree

**Comment by springmeyer** [comment]
These warnings are happening I think because node-pre-gyp is not being bundled. See https://github.com/mapbox/node-pre-gyp#configuring for how to properly configure with bundling.
