### ISSUE TITLE
binary section and multiple module targets in one project

### ISSUE THREAD

**Issue by rimmartin** [mapbox/node-pre-gyp#171]
Hi,
My project builds mutliple targets in one project.
module_name only takes one?  Maybe could be an array?

Currently I copy the rest over in script to the binding folder

**Comment by springmeyer** [comment]
Currently there is not support for an array. How important is this to you?

**Comment by rimmartin** [comment]
I just copy my *.node to the ./lib/binding and they all wind up in the distribution tars

works around

**Comment by springmeyer** [comment]
good workaround for now @rimmartin

**Comment by springmeyer** [comment]
I think the workaround is sufficient since this usecase is rare.
