### ISSUE TITLE
Installation results in outdated dependency

### ISSUE THREAD

**Issue by cbas** [mapbox/node-pre-gyp#179]
node-pre-gyp@0.6.12 [`package.json`](https://github.com/mapbox/node-pre-gyp/blob/56b36beb0c58f2a6245c4cac953bba7175b09572/package.json#L25)
```
  "dependencies": {
    ...
    "request": "2.x",
```
But somehow the installed dependency is `request@2.64.0`.
```bash
# Install latest version of node-pre-gyp (0.6.12)
npm install node-pre-gyp

# Check the request dependency requirement
cat ./node_modules/node-pre-gyp/package.json | grep request
    "request": "2.x",
    "request",

# Check latest available version of request
npm show request | grep version:
  version: '2.65.0',

# Check which request version was actually installed
npm ls | grep request
├─┬ request@2.64.0
```
Why is `request@2.64.0` being installed instead of `request@2.65.0`? Is this an NPM bug?

(I'm on OSX 10.11 and node 4.1.2)

**Comment by springmeyer** [comment]
Because node-pre-gyp bundles its dependencies. This is done to ensure that those dependencies are available when node-pre-gyp is run (during install). More info at #61

**Comment by springmeyer** [comment]
Oh, and I'll release `v0.6.13` in a moment that includes the latest request (bundled).

**Comment by cbas** [comment]
TIL bundled dependencies! :sparkles:
