### ISSUE TITLE
Update package.json

### ISSUE THREAD

**Issue by Emuentes** [mapbox/node-pre-gyp#186]
From https://nodesecurity.io/advisories/57:

    The tar module earlier than version 2.0.0 allow for archives to
    contain symbolic links that will overwrite targets outside the
    expected path for extraction.

https://github.com/mapbox/node-pre-gyp/pull/184

**Comment by springmeyer** [comment]
fixed by https://github.com/mapbox/node-pre-gyp/pull/183
