### ISSUE TITLE
No binary available

### ISSUE THREAD

**Issue by WebReflection** [mapbox/node-pre-gyp#192]
Even installing `npm install -g node-pre-gyp` the executable is never found. I have to link it from its libarry folder manually.

With `node-gyp` this is not needed, the moment I `npm install node-gyp` it's available as executable.

I'm pretty sure I'm not the only one filing this bug but I couldn't find any other related topic after my searches so apologies for a possibly redundant bug but I've no idea how to solve this.

Thank you!

**Comment by springmeyer** [comment]
First off I'm not sure why you are installing `node-pre-gyp` globally. It is fine to install it locally and call it like `./node_modules/.bin/node-pre-gyp`.

Also, i'm unable to replicate your problem:

```
$ node-pre-gyp
-bash: node-pre-gyp: command not found
~$ npm install -g node-pre-gyp
/Users/dane/.nvm/v0.10.40/bin/node-pre-gyp -> /Users/dane/.nvm/v0.10.40/lib/node_modules/node-pre-gyp/bin/node-pre-gyp
node-pre-gyp@0.6.18 /Users/dane/.nvm/v0.10.40/lib/node_modules/node-pre-gyp
~$ node-pre-gyp

  Usage: node-pre-gyp <command> [options]

  where <command> is one of:
    - clean - Removes the entire folder containing the compiled .node module
    - install - Attempts to install pre-built binary for module
    - reinstall - Runs "clean" and "install" at once
    - build - Attempts to compile the module by dispatching to node-gyp or nw-gyp
    - rebuild - Runs "clean" and "build" at once
    - package - Packs binary (and enclosing directory) into locally staged tarball
    - testpackage - Tests that the staged package is valid
    - publish - Publishes pre-built binary (requires aws-sdk)
    - unpublish - Unpublishes pre-built binary (requires aws-sdk)
    - info - Lists all published binaries (requires aws-sdk)
    - testbinary - Tests that the binary.node can be required
    - reveal - Reveals data on the versioned binary
    - configure - Attempts to configure node-gyp or nw-gyp build

node-pre-gyp@0.6.18  /Users/dane/.nvm/v0.10.40/lib/node_modules/node-pre-gyp
node@0.10.40
```

**Comment by WebReflection** [comment]
ok, here a hopefully better explanation.

If I install `npm install node-gyp` with or without the `-g` flag it's going to work. 

If I have `node-gyp` **and** the `node-pre-gyp` dependency installed **and** my `package.json` file has a `"script": { "install": "node-pre-gyp build" }` in there that's always going to fail because `node-pre-gyp doesn't install itself as a proper binary.

I have global npm prefix configured and nothing goes there as binary, so whatever instruction I can read about just `node-pre-gyp rebuild` thing doesn't work.

I'm on ArchLinux but Fedora is the same, I haven't tried on OSX yet, I might do that if you want me to.

Thanks

**Comment by springmeyer** [comment]
> If I install npm install node-gyp with or without the -g flag it's going to work.

node-gyp is part of the node install. node-pre-gyp is not, but it still should work with or without the -g flag just the same. However my hunch is that you are installing `node-gyp` with `-g` and thinking it is being found, but in fact the one provided by node core install may be the one being found.

> that's always going to fail because `node-pre-gyp doesn't install itself as a proper binary.

I don't understand and I can't replicate this. The install of node-pre-gyp does work as a binary/command line program. If it did not it would not work for anyone ever.  If you have `node-pre-gyp` in your `package.json` then it will get installed into `./node_modules/node-pre-gyp` and npm will automatically create `./node_modules/.bin/node-pre-gyp` and put `./node_modules/.bin/` and npm will make that available to itself when the `install` target is run. This is how things work and they work fine. So, something must be customized on your system.

> I have global npm prefix configured and nothing goes there as binary, so whatever instruction I can read about just node-pre-gyp rebuild thing doesn't work.

This may be your problem. Can you share more details on this? However that does not explain why `./node_modules/.bin/node-pre-gyp` is not being used/found. It should be.

**Comment by WebReflection** [comment]
I think I forgot about this and cannot even remember what/where/why/how so I'll close this for now and eventually will come back.

Thanks for your answers.
