### ISSUE TITLE
is it possible to use process.dlopen to load native library ?

### ISSUE THREAD

**Issue by mashaly100200** [mapbox/node-pre-gyp#194]
i try to use webpack with nw.js to not only bundle my own code but also to bundle all node_models .
 
every think work fine , except when load node_sqlite3.node  ,  it gives me an error " The specified module could not be found. "

webpack replace require("absulute_pathe_node_sqlite3.node") with process.dlopen("absulute_pathe_node_sqlite3.node")

i tried node-webkit version of node_sqlite3.node  and also node version but it gives me the same error
"The specified procedure could not be found"

**Comment by springmeyer** [comment]
This problem is likely that your binaries are not build for the right runtime. Please report this problem to the upstream module: in this case node-sqlite3.
