### ISSUE TITLE
Node.js 0.12.x -> 0.8.x

### ISSUE THREAD

**Issue by bchr02** [mapbox/node-pre-gyp#203]
Forgive my ignorance, but what does the below mean? It was taken from your current README.md. 

>Depends

>Node.js 0.12.x -> 0.8.x

Trying to figure out if node-pre-gyp supports node 0.10.x? Thanks.

**Comment by bchr02** [comment]
Within appveyor.yml it seems that there is testing for version 0.10 so I guess that answers the question, but to me your README is not clear on this.

**Comment by springmeyer** [comment]
We support node v0.10.x and greater - fixed in 90b6eb7

**Comment by bchr02** [comment]
Thanks!
