### ISSUE TITLE
Version of node headers and lib to use to build binaries

### ISSUE THREAD

**Issue by Flarna** [mapbox/node-pre-gyp#207]
I have a question regarding the version of node headers and lib (in case of windows) to use for pre built binaries.

It's clear that I have to build one .node file per NODE_MODULE_VERSION, but every node version provides it's set of headers - and lib in case of windows.

Node pre gyp provides a parameter to select the node version to be used for the build but any other node version with same NODE_MODULE_VERSION may in the end load the native extension then.

Is it relevant/important which set of headers I use for my build?
Should I prefer the newest or the latest version?

**Comment by mikemorris** [comment]
> Is it relevant/important which set of headers I use for my build?

Yes, you should build against the headers for the version of Node you intend to run against. Attempting to run a binary against a version of the Node.js lib different from the headers with module was built with will produce runtime errors.

**Comment by Flarna** [comment]
As far as I understood node-pre-gyp the only version used to distinguish between pre-built binaries is the NODE_MODULE_VERSION which is the same for all major versions (e.a. 4.x.y).
And this is also the only value checked by Node during loading a native extension.

If I understood you correct it would be needed to provide one binary per minor version and not just per NODE_MODULE_VERSION.

I took a fast look on what an existing user of node-pre-gyp (node-sqlite3) puts on S3 and it seems they also use just the NODE_MODULE_VERSION.

**Comment by mikemorris** [comment]
@Flarna Ah, sorry for the confusion, yea the headers must be from the same major version - I haven't seen any problems running against a newer/older lib minor version than the headers a library was compiled against, building against the newest headers for the given major version should be a safe bet.

**Comment by Flarna** [comment]
Thanks a lot!
