### ISSUE TITLE
node-pre-gyp configure error on "Electron Printer"

### ISSUE THREAD

**Issue by sumitsevolvan** [mapbox/node-pre-gyp#214]
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.6.28
node-pre-gyp info using node@0.12.4 | win32 | ia32
node-pre-gyp ERR! UNCAUGHT EXCEPTION
node-pre-gyp ERR! stack Error: electron-quick-start package.json is not node-pre-gyp ready:
node-pre-gyp ERR! stack package.json must declare these properties:
node-pre-gyp ERR! stack binary.module_name
node-pre-gyp ERR! stack binary.module_path
node-pre-gyp ERR! stack binary.host
node-pre-gyp ERR! stack     at validate_config (C:\Users\evo-9\AppData\Roaming\npm\node_modules\node-pre-gyp\lib\util\versionin
g.js:203:15)
node-pre-gyp ERR! stack     at Object.module.exports.evaluate (C:\Users\evo-9\AppData\Roaming\npm\node_modules\node-pre-gyp\lib
\util\versioning.js:261:5)
node-pre-gyp ERR! stack     at handle_gyp_opts (C:\Users\evo-9\AppData\Roaming\npm\node_modules\node-pre-gyp\lib\util\handle_gy
p_opts.js:54:27)
node-pre-gyp ERR! stack     at configure (C:\Users\evo-9\AppData\Roaming\npm\node_modules\node-pre-gyp\lib\configure.js:11:5)
node-pre-gyp ERR! stack     at Object.self.commands.(anonymous function) [as configure] (C:\Users\evo-9\AppData\Roaming\npm\nod
e_modules\node-pre-gyp\lib\node-pre-gyp.js:48:37)
node-pre-gyp ERR! stack     at run (C:\Users\evo-9\AppData\Roaming\npm\node_modules\node-pre-gyp\bin\node-pre-gyp:79:30)
node-pre-gyp ERR! stack     at Object.<anonymous> (C:\Users\evo-9\AppData\Roaming\npm\node_modules\node-pre-gyp\bin\node-pre-gy
p:131:1)
node-pre-gyp ERR! stack     at Module._compile (module.js:460:26)
node-pre-gyp ERR! stack     at Object.Module._extensions..js (module.js:478:10)
node-pre-gyp ERR! stack     at Module.load (module.js:355:32)
node-pre-gyp ERR! System Windows_NT 6.1.7601
node-pre-gyp ERR! command "node" "C:\\Users\\evo-9\\AppData\\Roaming\\npm\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "conf
igure"
node-pre-gyp ERR! cwd C:\waamp\www\Electron\electron-quick-start
node-pre-gyp ERR! node -v v0.12.4
node-pre-gyp ERR! node-pre-gyp -v v0.6.28
node-pre-gyp ERR! This is a bug in `node-pre-gyp`.
node-pre-gyp ERR! Try to update node-pre-gyp and file an issue if it does not help:
node-pre-gyp ERR!     <https://github.com/mapbox/node-pre-gyp/issues>

**Comment by springmeyer** [comment]
I think your problem is you ran `node-pre-gyp` from the wrong directory. It looks like your current directory was `C:\waamp\www\Electron\electron-quick-start`. That module does not depend on node-pre-gyp. It appears you are trying to install https://github.com/marcopiraccini/electron-printer which does depend on node-pre-gyp. So make sure you only try to use node-pre-gyp with https://github.com/marcopiraccini/electron-printer (or other modules that depend on it). Rule of thumb is to just run `npm install` instead of `node-pre-gyp install` (the former calls the latter when needed).
