### ISSUE TITLE
Does node-pre-gyp handle proxys and ca-bundles?

### ISSUE THREAD

**Issue by Jackbennett** [mapbox/node-pre-gyp#221]
Hey I'm on a network that MITM's traffic, the npm global ca-bundle is set to the right .pem and I can happily use npm all day. Strict-ssl = false is set for good measure.

Trying to install serialport and I always fail to download the precompiled files.

```
> serialport@3.1.2 install N:\Documents\src\ohbot-5\node_modules\serialport
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download: https://github.com/voodootikigod/node-serialport/releases/download/3.1.2/serialport-v3.1.2-node-v48-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for serialport@3.1.2 and node@6.2.1 (node-v48 ABI) (falling back to source compile with node-gyp)
```
then of course I fail to  compile because that's a different headache.

`https://github.com/voodootikigod/node-serialport/releases/download/3.1.2/serialport-v3.1.2-node-v48-win32-x64.tar.gz` does indeed download when pasted into chrome. So can anyone help me out? Is node-pre-gyp correctly ignoring certificate errors as configured by the config already in npmrc.

I find most node does a good job of ignoring system internet settings and things called by node are quite reliable to check how node is configured.

**Comment by BergWerkGIS** [comment]
Have you tried setting the environment variables `HTTP_PROXY`/`HTTPS_PROXY` before installing? 

node-pre-gyp [honors this setting when downloading](https://github.com/mapbox/node-pre-gyp/blob/cfbcac3bc32920a21e987f2273ed10f89c24e433/lib/install.js#L29).

Although I have no idea how to let node know about the ca-bundles.

**Comment by Jackbennett** [comment]
I don't actually use a proxy setting. My issue is the ca-bundle/ssl
filtering. They just usually go hand in hand these problems.

On 24 June 2016 at 14:15, Wilhelm Berg <notifications@github.com> wrote:

> Have you tried setting the environment variables HTTP_PROXY/HTTPS_PROXY
> before installing?
>
> node-pre-gyp honors this setting when downloading
> <https://github.com/mapbox/node-pre-gyp/blob/cfbcac3bc32920a21e987f2273ed10f89c24e433/lib/install.js#L29>
> .
>
> Although I have no idea how to let node know about the ca-bundles.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/mapbox/node-pre-gyp/issues/221#issuecomment-228342128>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAwSXnNEuz-kQA4-l7eq-TcK2RXQS-74ks5qO9hqgaJpZM4I70Ut>
> .
>



-- 
Jack Bennett
Developer

**Comment by springmeyer** [comment]
@Jackbennett node-pre-gyp is using request - which npm is using as well - so I'm not sure why this is failing / what is different. Can you try again and pass `--loglevel=verbose` then paste the entire log? That will show the http error code and perhaps more clues.

**Comment by springmeyer** [comment]
Also the code in `install.js` was originally copied from node-gyp. So perhaps https://github.com/nodejs/node-gyp/commit/8c4b0ffa503aa385f4186e028542dcedca2efeee needs to be ported to node-pre-gyp?

**Comment by Jackbennett** [comment]
This seems to be the smoking gun, I'd post the full log but I tried --loglevel silly and now nothing I do will unset that.....

```
> serialport@3.1.2 install U:\testcode\cafile\node_modules\serialport
> node-pre-gyp install --fallback-to-build

node-pre-gyp info it worked if it ends with ok
node-pre-gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
node-pre-gyp verb cli   'U:\\testcode\\cafile\\node_modules\\serialport\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp',
node-pre-gyp verb cli   'install',
node-pre-gyp verb cli   '--fallback-to-build' ]
node-pre-gyp info using node-pre-gyp@0.6.28
node-pre-gyp info using node@6.2.2 | win32 | x64
node-pre-gyp verb command install []
node-pre-gyp info check checked for "U:\testcode\cafile\node_modules\serialport\build\Release\serialport.node" (not found)
node-pre-gyp http GET https://github.com/voodootikigod/node-serialport/releases/download/3.1.2/serialport-v3.1.2-node-v48-win32-x64.tar.gz
node-pre-gyp ERR! Tried to download: https://github.com/voodootikigod/node-serialport/releases/download/3.1.2/serialport-v3.1.2-node-v48-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for serialport@3.1.2 and node@6.2.2 (node-v48 ABI) (falling back to source compile with node-gyp)
node-pre-gyp http self signed certificate in certificate chain
node-pre-gyp verb command build [ 'rebuild' ]
...
```
Unrelated - How funny powershell eats the error message somehow; 
![image](https://cloud.githubusercontent.com/assets/791134/16444103/547fb914-3dd4-11e6-83eb-c0ffe1c5f1ce.png)

**Comment by Jackbennett** [comment]
I couldn't muddle something together but if you make me a branch I can check that out and test it here.

**Comment by Jackbennett** [comment]
Can I help move forward with this? It could save me deploying the build tools for an entire school.

**Comment by springmeyer** [comment]
Movement on this at #243. Will close this ticket, let's discuss at #243
