### ISSUE TITLE
Failed to install node-sqlite3 when using node-pre-gyp v0.6.4+ on ARMv6 (Raspi 1)

### ISSUE THREAD

**Issue by TomFreudenberg** [mapbox/node-pre-gyp#222]
Hi, I am maintaining the [meteor.js universal fork for running meteor on ARM](https://github.com/4commerce-technologies-AG/meteor). Therefor node-sqlite3 is used long time. Although the newest releases are working on ARMv7 and ARMv8 (Aarch64) the npm could not be installed on ARMv6 anymore.

After placing this issue at the sqlite3 project: https://github.com/mapbox/node-sqlite3/issues/671 I could detect that the issue is based on this package `node-pre-gyp`

If using release `v0.6.3` or previous the compilation and build of the sqlite3 packages runs.

When using release `v0.6.4` or newer, build break - see log

ATTENTION:

Even that there is this warning about access of "/root/.node-gyp/0.10.45" this is not "correct". I checked the directoy via

```
mkdir -p /root/.node-gyp/0.10.45
chmod 2777 /root/.node-gyp
chmod 2777 /root/.node-gyp/0.10.45
```

will not change anything to that warning. When looking at the successfull built (using v0.6.3) this warning exist too.

#### missed using v0.6.4

<pre>
PATH=$PATH:/tmp/node/bin npm install /tmp/node-sqlite3
npm WARN lifecycle sqlite3@3.1.4~prepublish: cannot run in wd %s %s (wd=%s) sqlite3@3.1.4 npm ls /tmp/node-sqlite3

> sqlite3@3.1.4 install /tmp/node/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/0.10.45"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/tmp/node/node_modules/sqlite3/.node-gyp"
make: Entering directory '/tmp/node/node_modules/sqlite3/build'
make: *** No rule to make target '../.node-gyp/0.10.45/include/node/common.gypi', needed by 'Makefile'.  Stop.
make: Leaving directory '/tmp/node/node_modules/sqlite3/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/tmp/node/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 4.4.13+
gyp ERR! command "/tmp/node/bin/node" "/tmp/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/tmp/node/node_modules/sqlite3/lib/binding/node-v11-linux-arm/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/tmp/node/node_modules/sqlite3/lib/binding/node-v11-linux-arm"
gyp ERR! cwd /tmp/node/node_modules/sqlite3
gyp ERR! node -v v0.10.45
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/tmp/node/bin/node /tmp/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/tmp/node/node_modules/sqlite3/lib/binding/node-v11-linux-arm/node_sqlite3.node --module_name=node_sqlite3 --module_path=/tmp/node/node_modules/sqlite3/lib/binding/node-v11-linux-arm' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/tmp/node/node_modules/node-pre-gyp/lib/util/compile.js:73:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:766:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:833:5)
node-pre-gyp ERR! System Linux 4.4.13+
node-pre-gyp ERR! command "node" "/tmp/node/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /tmp/node/node_modules/sqlite3
node-pre-gyp ERR! node -v v0.10.45
node-pre-gyp ERR! node-pre-gyp -v v0.6.4
node-pre-gyp ERR! not ok
Failed to execute '/tmp/node/bin/node /tmp/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/tmp/node/node_modules/sqlite3/lib/binding/node-v11-linux-arm/node_sqlite3.node --module_name=node_sqlite3 --module_path=/tmp/node/node_modules/sqlite3/lib/binding/node-v11-linux-arm' (1)
npm WARN enoent ENOENT, open '/tmp/node/package.json'
npm WARN node No description
npm WARN node No repository field.
npm WARN node No README data
npm WARN node No license field.
npm ERR! Linux 4.4.13+
npm ERR! argv "node" "/tmp/node/bin/npm" "install" "/tmp/node-sqlite3"
npm ERR! node v0.10.45
npm ERR! npm  v3.10.2
npm ERR! code ELIFECYCLE

npm ERR! sqlite3@3.1.4 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sqlite3@3.1.4 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sqlite3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sqlite3
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sqlite3
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/node/npm-debug.log
</pre>

#### success build using v0.6.3

<pre>
PATH=$PATH:/tmp/node/bin npm install /tmp/node-sqlite3
npm WARN lifecycle sqlite3@3.1.4~prepublish: cannot run in wd %s %s (wd=%s) sqlite3@3.1.4 npm ls /tmp/node-sqlite3

> sqlite3@3.1.4 install /tmp/node/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/0.10.45"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/tmp/node/node_modules/sqlite3/.node-gyp"
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/0.10.45"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/tmp/node/node_modules/sqlite3/.node-gyp"
make: Entering directory '/tmp/node/node_modules/sqlite3/build'
  ACTION deps_sqlite3_gyp_action_before_build_target_unpack_sqlite_dep Release/obj/gen/sqlite-autoconf-3090100/sqlite3.c
  TOUCH Release/obj.target/deps/action_before_build.stamp
  CC(target) Release/obj.target/sqlite3/gen/sqlite-autoconf-3090100/sqlite3.o
  AR(target) Release/obj.target/deps/sqlite3.a
  COPY Release/sqlite3.a
  CXX(target) Release/obj.target/node_sqlite3/src/database.o
../src/database.cc: In static member function ‘static void node_sqlite3::Database::Work_BeginOpen(node_sqlite3::Database::Baton*)’:
../src/database.cc:143:9: warning: unused variable ‘status’ [-Wunused-variable]
     int status = uv_queue_work(uv_default_loop(),
         ^
../src/database.cc: In static member function ‘static void node_sqlite3::Database::Work_BeginClose(node_sqlite3::Database::Baton*)’:
../src/database.cc:227:9: warning: unused variable ‘status’ [-Wunused-variable]
     int status = uv_queue_work(uv_default_loop(),
         ^
../src/database.cc: In static member function ‘static void node_sqlite3::Database::Work_BeginExec(node_sqlite3::Database::Baton*)’:
../src/database.cc:505:9: warning: unused variable ‘status’ [-Wunused-variable]
     int status = uv_queue_work(uv_default_loop(),
         ^
../src/database.cc: In static member function ‘static void node_sqlite3::Database::Work_BeginLoadExtension(node_sqlite3::Database::Baton*)’:
../src/database.cc:605:9: warning: unused variable ‘status’ [-Wunused-variable]
     int status = uv_queue_work(uv_default_loop(),
         ^
  CXX(target) Release/obj.target/node_sqlite3/src/node_sqlite3.o
  CXX(target) Release/obj.target/node_sqlite3/src/statement.o
../src/statement.cc: In static member function ‘static void node_sqlite3::Statement::Work_BeginPrepare(node_sqlite3::Database::Baton*)’:
../src/statement.cc:118:9: warning: unused variable ‘status’ [-Wunused-variable]
     int status = uv_queue_work(uv_default_loop(),
         ^
In file included from ../src/statement.cc:6:0:
../src/statement.cc: In static member function ‘static void node_sqlite3::Statement::Work_BeginBind(node_sqlite3::Statement::Baton*)’:
../src/macros.h:125:9: warning: unused variable ‘status’ [-Wunused-variable]
     int status = uv_queue_work(uv_default_loop(),                              \
         ^
../src/statement.cc:322:5: note: in expansion of macro ‘STATEMENT_BEGIN’
     STATEMENT_BEGIN(Bind);
     ^
../src/statement.cc: In static member function ‘static void node_sqlite3::Statement::Work_BeginGet(node_sqlite3::Statement::Baton*)’:
../src/macros.h:125:9: warning: unused variable ‘status’ [-Wunused-variable]
     int status = uv_queue_work(uv_default_loop(),                              \
         ^
../src/statement.cc:370:5: note: in expansion of macro ‘STATEMENT_BEGIN’
     STATEMENT_BEGIN(Get);
     ^
../src/statement.cc: In static member function ‘static void node_sqlite3::Statement::Work_BeginRun(node_sqlite3::Statement::Baton*)’:
../src/macros.h:125:9: warning: unused variable ‘status’ [-Wunused-variable]
     int status = uv_queue_work(uv_default_loop(),                              \
         ^
../src/statement.cc:438:5: note: in expansion of macro ‘STATEMENT_BEGIN’
     STATEMENT_BEGIN(Run);
     ^
../src/statement.cc: In static member function ‘static void node_sqlite3::Statement::Work_BeginAll(node_sqlite3::Statement::Baton*)’:
../src/macros.h:125:9: warning: unused variable ‘status’ [-Wunused-variable]
     int status = uv_queue_work(uv_default_loop(),                              \
         ^
../src/statement.cc:504:5: note: in expansion of macro ‘STATEMENT_BEGIN’
     STATEMENT_BEGIN(All);
     ^
../src/statement.cc: In static member function ‘static void node_sqlite3::Statement::Work_BeginEach(node_sqlite3::Statement::Baton*)’:
../src/macros.h:125:9: warning: unused variable ‘status’ [-Wunused-variable]
     int status = uv_queue_work(uv_default_loop(),                              \
         ^
../src/statement.cc:601:5: note: in expansion of macro ‘STATEMENT_BEGIN’
     STATEMENT_BEGIN(Each);
     ^
../src/statement.cc: In static member function ‘static void node_sqlite3::Statement::Work_BeginReset(node_sqlite3::Statement::Baton*)’:
../src/macros.h:125:9: warning: unused variable ‘status’ [-Wunused-variable]
     int status = uv_queue_work(uv_default_loop(),                              \
         ^
../src/statement.cc:724:5: note: in expansion of macro ‘STATEMENT_BEGIN’
     STATEMENT_BEGIN(Reset);
     ^
  SOLINK_MODULE(target) Release/obj.target/node_sqlite3.node
  COPY Release/node_sqlite3.node
  COPY /tmp/node/node_modules/sqlite3/lib/binding/node-v11-linux-arm/node_sqlite3.node
  TOUCH Release/obj.target/action_after_build.stamp
make: Leaving directory '/tmp/node/node_modules/sqlite3/build'
/tmp/node
└─┬ sqlite3@3.1.4
  ├── nan@2.3.5
  └─┬ node-pre-gyp@0.6.3
    ├─┬ mkdirp@0.5.0
    │ └── minimist@0.0.8
    ├─┬ nopt@3.0.1
    │ └── abbrev@1.0.5
    ├─┬ npmlog@0.1.1
    │ └── ansi@0.3.0
    ├─┬ rc@0.5.5
    │ ├── deep-extend@0.2.11
    │ ├── ini@1.3.3
    │ ├── minimist@0.0.10
    │ └── strip-json-comments@0.1.3
    ├─┬ request@2.53.0
    │ ├── aws-sign2@0.5.0
    │ ├─┬ bl@0.9.4
    │ │ └─┬ readable-stream@1.0.33
    │ │   ├── core-util-is@1.0.1
    │ │   ├── inherits@2.0.1
    │ │   ├── isarray@0.0.1
    │ │   └── string_decoder@0.10.31
    │ ├── caseless@0.9.0
    │ ├─┬ combined-stream@0.0.7
    │ │ └── delayed-stream@0.0.5
    │ ├── forever-agent@0.5.2
    │ ├─┬ form-data@0.2.0
    │ │ └── async@0.9.0
    │ ├─┬ hawk@2.3.1
    │ │ ├── boom@2.6.1
    │ │ ├── cryptiles@2.0.4
    │ │ ├── hoek@2.11.0
    │ │ └── sntp@1.0.9
    │ ├─┬ http-signature@0.10.1
    │ │ ├── asn1@0.1.11
    │ │ ├── assert-plus@0.1.5
    │ │ └── ctype@0.5.3
    │ ├── isstream@0.1.1
    │ ├── json-stringify-safe@5.0.0
    │ ├─┬ mime-types@2.0.9
    │ │ └── mime-db@1.7.0
    │ ├── node-uuid@1.4.2
    │ ├── oauth-sign@0.6.0
    │ ├── qs@2.3.3
    │ ├── stringstream@0.0.4
    │ ├─┬ tough-cookie@0.12.1
    │ │ └── punycode@1.3.2
    │ └── tunnel-agent@0.4.0
    ├── rimraf@2.2.8
    ├── semver@4.2.2
    ├─┬ tar@1.0.3
    │ ├── block-stream@0.0.7
    │ ├─┬ fstream@1.0.4
    │ │ └── graceful-fs@3.0.5
    │ └── inherits@2.0.1
    └─┬ tar-pack@2.0.0
      ├── debug@0.7.4
      ├─┬ fstream@0.1.31
      │ ├── graceful-fs@3.0.5
      │ └── inherits@2.0.1
      ├─┬ fstream-ignore@0.0.7
      │ ├── inherits@2.0.1
      │ └─┬ minimatch@0.2.14
      │   ├── lru-cache@2.5.0
      │   └── sigmund@1.0.0
      ├── graceful-fs@1.2.3
      ├── once@1.1.1
      ├─┬ readable-stream@1.0.33
      │ ├── core-util-is@1.0.1
      │ ├── inherits@2.0.1
      │ ├── isarray@0.0.1
      │ └── string_decoder@0.10.31
      ├─┬ tar@0.1.20
      │ ├── block-stream@0.0.7
      │ └── inherits@2.0.1
      └── uid-number@0.0.3

npm WARN enoent ENOENT, open '/tmp/node/package.json'
npm WARN node No description
npm WARN node No repository field.
npm WARN node No README data
npm WARN node No license field.
</pre>

**Comment by springmeyer** [comment]
The problem is `cannot run in wd` - npm cannot be run as root otherwise it blocks access to node-pre-gyp. So either don't run as root or pass `--unsafe-perm` per #165

**Comment by TomFreudenberg** [comment]
Hi Dane @springmeyer can't believe this simple answer

Hopefully you have read my complete message, I am wondering why on all systems I am working on same sonditions will work but not on the armv6l box?

And why ist all fine when using node-pre-gyp 0.6.3 but not 0.6.4+ ???

Could you please be so kind and answer that for me.

In addition, I will make the check as user pi for your and post that result in here as well.

**Comment by TomFreudenberg** [comment]
Hi Dane @springmeyer I can confirm correct installation of sqlite3 and running node-pre-gyp when running the npm task as user pi.

I was so couriosed about, that I checked some more and:

If doing:

```
ssh pi@machine

sudo bash

npm install sqlite3
```

you will fail as described.

I you will login as root (su instead sudo):

```
ssh pi@machine

su

npm install sqlite3
```

This will work too even without any warnings

<pre>
root@raspberrypi:/tmp/demo# npm install sqlite3

> sqlite3@3.1.4 install /tmp/demo/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download: https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.4/node-v11-linux-arm.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for sqlite3@3.1.4 and node@0.10.45 (node-v11 ABI) (falling back to source compile with node-gyp)
make: Entering directory '/tmp/demo/node_modules/sqlite3/build'
  ACTION deps_sqlite3_gyp_action_before_build_target_unpack_sqlite_dep Release/obj/gen/sqlite-autoconf-3090100/sqlite3.c
  TOUCH Release/obj.target/deps/action_before_build.stamp
  CC(target) Release/obj.target/sqlite3/gen/sqlite-autoconf-3090100/sqlite3.o
...
</pre>

Do you have any explanation about this? why "sudo" may fail but not "su"?

I am totally irritated

**Comment by TomFreudenberg** [comment]
@springmeyer Hi Dane,

would be great if you could give me your thoughts about my last entry.

Still irritated about that behavior

Thanks in advance
Tom

**Comment by pinich** [comment]
I had similar issue,
In my case when I ran the npm install I have added '--unsafe-perm=true --allow-root'

I think the you should run with the **--allow-root**
`npm i --unsafe-perm=true --allow-root`
