### ISSUE TITLE
Defecting  the wrong node ppc64 tar.gz

### ISSUE THREAD

**Issue by smartmouse** [mapbox/node-pre-gyp#224]
> sqlite3@3.1.4 install /home/slbld/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download: https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.4/node-v48-linux-ppc64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for sqlite3@3.1.4 and node@6.0.0 (node-v48 ABI) (falling back to source compile with node-gyp) 
make: Entering directory `/home/slbld/node_modules/sqlite3/build'
  ACTION deps_sqlite3_gyp_action_before_build_target_unpack_sqlite_dep Release/obj/gen/sqlite-autoconf-3090100/sqlite3.c

In the above it pulls down /node-v48-linux-ppc64.tar.gz 

but our system is ppc64 LE
should be ppc64le.tar.gz

slbld@apicrhel7le02 ~]$ node -e "console.log(process.config)"
{ target_defaults:
   { cflags: [],
     default_configuration: 'Release',
     defines: [],
     include_dirs: [],
     libraries: [] },
  variables:
   { asan: 0,
     gas_version: '2.24',
     host_arch: 'ppc64',
     icu_data_file: 'icudt56l.dat',
     icu_data_in: '../../deps/icu/source/data/in/icudt56l.dat',
     icu_endianness: 'l',
     icu_gyp_path: 'tools/icu/icu-generic.gyp',
     icu_locales: 'en,root',
     icu_path: './deps/icu',
     icu_small: true,
     icu_ver_major: '56',
     node_byteorder: 'little',
     node_install_npm: true,
     node_prefix: '/',
     node_release_urlbase: '',
     node_shared_http_parser: false,
     node_shared_libuv: false,
     node_shared_openssl: false,
     node_shared_zlib: false,
     node_tag: '-IBMBuild-4.4.4.0-201605060633',
     node_use_dtrace: false,
     node_use_etw: false,
     node_use_lttng: false,
     node_use_openssl: true,
     node_use_perfctr: false,
     node_use_static_libstdcpp: false,
     openssl_fips: '',
     openssl_no_asm: 0,
     target_arch: 'ppc64',
     uv_parent_path: '/deps/uv/',
     uv_use_dtrace: false,
     v8_enable_gdbjit: 0,
     v8_enable_i18n_support: 1,
     v8_no_strict_aliasing: 1,
     v8_optimized_debug: 0,
     v8_parent_path: 'deps/v8',
     v8_random_seed: 0,
     v8_use_snapshot: true,
     want_separate_host_toolset: 0 } }
[slbld@apicrhel7le02 ~]$

**Comment by springmeyer** [comment]
> but our system is ppc64 LE
> should be ppc64le.tar.gz

The `ppc64` value is coming from node's `process.arch`. So if you think that value is wrong then you'll need to report to node core issues.
