### ISSUE TITLE
Endless loop of installing node-pre-gyp

### ISSUE THREAD

**Issue by FrontierPsychiatrist** [mapbox/node-pre-gyp#226]
For my NodeJS module node-spotify I recently updated the `package.json` to follow the readme of this project. You can check it our here https://github.com/FrontierPsychiatrist/node-spotify/blob/28d759b503d62c0b0a0af8f6888081d7bc2644f7/package.json

After publishing this change (v0.8.2) it resulted in an endless loop (well, I guess endless) of installing node-pre-gyp:

```
% npm install node-spotify

> node-spotify@0.8.2 preinstall /home/moritz/temp/node_modules/.staging/node-spotify-c47dd7f0
> npm install node-pre-gyp


> node-spotify@0.8.2 preinstall /home/moritz/temp/node_modules/.staging/node-spotify-c47dd7f0/node_modules/.staging/node-spotify-e25d73ad
> npm install node-pre-gyp


> node-spotify@0.8.2 preinstall /home/moritz/temp/node_modules/.staging/node-spotify-c47dd7f0/node_modules/.staging/node-spotify-e25d73ad/node_modules/.staging/node-spotify-7c1c2340
> npm install node-pre-gyp


> node-spotify@0.8.2 preinstall /home/moritz/temp/node_modules/.staging/node-spotify-c47dd7f0/node_modules/.staging/node-spotify-e25d73ad/node_modules/.staging/node-spotify-7c1c2340/node_modules/.staging/node-spotify-ad859c50

...
```

Any hint on what I'm doing wrong?

**Comment by mikemorris** [comment]
This looks like https://github.com/npm/npm/issues/12583. Try using npm v2 instead of v3.

**Comment by FrontierPsychiatrist** [comment]
Thanks for the link, I'll look into it.

In general I'm not sure if that's a good solution, I don't want to tell all my users to downgrade npm just to install my library. So for now I'll stay with having node-pre-gyp in the list of bundled dependencies (although this fails with NodeJS 4 apparently, see https://github.com/FrontierPsychiatrist/node-spotify/issues/104).
