### ISSUE TITLE
What are all of the variables node-pre-gyp can pass to gyp?

### ISSUE THREAD

**Issue by murgatroid99** [mapbox/node-pre-gyp#230]
I know that node-pre-gyp passes `module_name` and `module_path` to gyp, so that the suggested `action_after_build` target can work. Does it pass any other variables, and if so what are they? For example, if I run `node-pre-gyp build --runtime=electron`, is that information available to gyp in any way?

**Comment by springmeyer** [comment]
node-pre-gyp attempts to pass all command line options down to node-gyp. So, yes `--runtime=electron` would be passed through. The log is at https://github.com/mapbox/node-pre-gyp/blob/master/lib/util/handle_gyp_opts.js

**Comment by murgatroid99** [comment]
Thanks for your help. I think I saw that file before, but I managed to confuse myself when I looked at the call sites, and I thought some arguments were getting discarded.
