### ISSUE TITLE
node-pre-gyp never downloads electron development headers

### ISSUE THREAD

**Issue by murgatroid99** [mapbox/node-pre-gyp#233]
The option `--runtime` is supposed to change what runtime to configure and build for. But if I run `node-pre-gyp configure --runtime=electron --target=1.3.2`, the operation fails with `Error: 404 response downloading https://iojs.org/dist/v1.3.2/iojs-v1.3.2.tar.gz`. This happens because node-pre-gyp completely delegates downloading those development headers to node-gyp, and never informs node-gyp that it should be downloading electron headers. By default, node-gyp chooses a download source based on the version provided, and never attempts to download electron development headers.

**Comment by lyssdod** [comment]
Try passing `--build-from-source` to `node-gyp-rebuild` as specified at http://electron.atom.io/docs/tutorial/using-native-node-modules/

**Comment by murgatroid99** [comment]
That's not really what I was asking. My question is about `node-pre-gyp`'s ability to build and publish packages for Node versions and runtimes other than the one that the build is running on.

**Comment by lyssdod** [comment]
I think you can use `--dist-url=https://atom.io/download/atom-shell` option to make it fetch exactly electron's headers

**Comment by springmeyer** [comment]
Yes, dist-url should work. Also `--runtime` will be passed to node-gyp per #230. But node-gyp does not - as far as I know - do anything with that option.
