### ISSUE TITLE
Bump a new version to avoid package require error

### ISSUE THREAD

**Issue by rodrigopivi** [mapbox/node-pre-gyp#262]
Tested this with Realm-js 0.15.4, using Yarn v0.19.1 and also tested with NPM 3.10.10.

When using Realm-js with tests, i get an exception like:
```
Cannot find module '../package' from 'node-pre-gyp.js'
```

This is because version `v0.6.32` still points to `../package` instead of `../package.json`
https://github.com/mapbox/node-pre-gyp/blob/v0.6.32/lib/node-pre-gyp.js#L62

This seems to be already fixed on master:
```
https://github.com/mapbox/node-pre-gyp/blob/master/lib/node-pre-gyp.js#L62
```

Since this is already fixed on master, but still causing issues with latest (0.6.32) release, can you please bump the version to also fix this for actual non-master branch users ?

**Comment by springmeyer** [comment]
Thanks for reporting. v0.6.33 is now released @rodrigopivi
