### ISSUE TITLE
pre-gyp looks for the wrong ABI in electron childProcess.forks

### ISSUE THREAD

**Issue by bcomnes** [mapbox/node-pre-gyp#278]
It appears node-pre-gyp modules are trying to use the wrong ABI when run inside of a childProcess.fork from an electron process, even if you have rebuilt the correct ABI using something like [electron-rebuild](https://github.com/electron/electron-rebuild).  It looks like this problem has been around a while, and even a [few](https://github.com/electron/electron-rebuild/commit/496439a7c20a8ce08ea3bc242a440187948dff53) [hacks](https://github.com/electron/electron-rebuild/blob/27fd3114b68bf5f9c438255b412cea763e768826/src/node-pre-gyp-fix.js) came and went.

Here is an example of the issue with sqlite3: https://github.com/ballpit/electron-sqlite3-fork-bug/blob/master/main.js

It looks like [node-gyp-build had a similar issue](https://github.com/electron/electron/issues/8727) a while back, and they ended up implementing a check for the [process.env.ELECTRON_RUN_AS_NODE](https://github.com/mafintosh/node-gyp-build/blob/master/index.js#L51) and returning electron bindings when thats found, and it looks like maybe we need to port that over to node-pre-gyp as well to fix this problem.  

It looks like the ABI selection is happening in https://github.com/mapbox/node-pre-gyp/blob/master/lib/util/versioning.js. Any idea where such a check might live in that file?

**Comment by Tomyail** [comment]
any update for this issue? I need this pull request

**Comment by Tomyail** [comment]
I create a [pull request](https://github.com/mapbox/node-pre-gyp/pull/343) for this issue

**Comment by bcomnes** [comment]
This is my original PR to close this: https://github.com/mapbox/node-pre-gyp/pull/279

Open to either solution, but I think we should aim to make this work without user provided env vars.

**Comment by bcomnes** [comment]
This should be resolved, however I haven't personally tested.

**Comment by awohletz** [comment]
Confirmed that updating to Electron v6 (currently in beta) fixed the issue for me. E.g. I am able to use node-sqlite3 from an Electron-forked process.

**Comment by bcomnes** [comment]
@awohletz that's great news thank you for the info!
