### ISSUE TITLE
Can you add Node v8.0.0 to the ABI crosswalk

### ISSUE THREAD

**Issue by murgatroid99** [mapbox/node-pre-gyp#294]
Node 8 just came out, so it would be good to be able to build for it.

**Comment by springmeyer** [comment]
done in https://github.com/mapbox/node-pre-gyp/commit/53d9cad8052817ee398cd519b4f1736ec7934744. Will release v0.6.33 in the next few minutes with this crosswalk bundled.

**Comment by murgatroid99** [comment]
npm says that v0.6.34 was already published back in March.

**Comment by springmeyer** [comment]
thanks, still working on release - so I would have hit that. It will be v0.6.35 then.

**Comment by springmeyer** [comment]
v0.6.35 is now published https://www.npmjs.com/package/node-pre-gyp
