### ISSUE TITLE
Electron binaries fail validation in v0.6.35 

### ISSUE THREAD

**Issue by p120ph37** [mapbox/node-pre-gyp#295]
In a projects with `runtime=electron`, the `node --eval require` from `testbinary.js` results in a library load error because it tries to use node to load the library rather than electron.  This is new in v0.6.35.  At the very least, this test should be skipped if runtime != node until a more robust electron test is available.

**Comment by springmeyer** [comment]
Thanks for catching this regression. Can you test https://github.com/mapbox/node-pre-gyp/pull/296 to see if that fixes things?
