### ISSUE TITLE
node-pre-gyp ERR! stack TypeError: Cannot read property 'major' of null

### ISSUE THREAD

**Issue by azurinko** [mapbox/node-pre-gyp#307]
c:\testing\electron\node_modules\sqlite3 (master) (sqlite3@3.1.8)
λ node-pre-gyp configure --runtime=electron --msvs-version 2015 --target v1.4
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.6.36
node-pre-gyp info using node@8.1.2 | win32 | x64
node-pre-gyp ERR! UNCAUGHT EXCEPTION
node-pre-gyp ERR! stack TypeError: Cannot read property 'major' of null
node-pre-gyp ERR! stack     at get_electron_abi (C:\Users\yamami\AppData\Roaming\npm\node_modules\node-pre-gyp\lib\util\versioning.js:30:36)
node-pre-gyp ERR! stack     at get_runtime_abi (C:\Users\yamami\AppData\Roaming\npm\node_modules\node-pre-gyp\lib\util\versioning.js:73:16)
node-pre-gyp ERR! stack     at Object.module.exports.evaluate (C:\Users\yamami\AppData\Roaming\npm\node_modules\node-pre-gyp\lib\util\versioning.js:277:19)
node-pre-gyp ERR! stack     at handle_gyp_opts (C:\Users\yamami\AppData\Roaming\npm\node_modules\node-pre-gyp\lib\util\handle_gyp_opts.js:54:27)
node-pre-gyp ERR! stack     at configure (C:\Users\yamami\AppData\Roaming\npm\node_modules\node-pre-gyp\lib\configure.js:11:5)
node-pre-gyp ERR! stack     at Object.self.commands.(anonymous function) [as configure] (C:\Users\yamami\AppData\Roaming\npm\node_modules\node-pre-gyp\lib\node-pre-gyp.js:50:37)
node-pre-gyp ERR! stack     at run (C:\Users\yamami\AppData\Roaming\npm\node_modules\node-pre-gyp\bin\node-pre-gyp:79:30)
node-pre-gyp ERR! stack     at Object.<anonymous> (C:\Users\yamami\AppData\Roaming\npm\node_modules\node-pre-gyp\bin\node-pre-gyp:131:1)
node-pre-gyp ERR! stack     at Module._compile (module.js:569:30)
node-pre-gyp ERR! stack     at Object.Module._extensions..js (module.js:580:10)
node-pre-gyp ERR! System Windows_NT 10.0.10586
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\yamami\\AppData\\Roaming\\npm\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "configure" "--runtime=electron" "--msvs-version" "2015" "--target" "v1.4"
node-pre-gyp ERR! cwd c:\testing\electron\node_modules\sqlite3
node-pre-gyp ERR! node -v v8.1.2
node-pre-gyp ERR! node-pre-gyp -v v0.6.36
node-pre-gyp ERR! This is a bug in `node-pre-gyp`.
node-pre-gyp ERR! Try to update node-pre-gyp and file an issue if it does not help:
node-pre-gyp ERR!     <https://github.com/mapbox/node-pre-gyp/issues>

**Comment by springmeyer** [comment]
`--target v1.4` needs to be `--target v1.4.0` or some full `MAJOR.MINOR.PATCH` semver.
