### ISSUE TITLE
Please bump `request` dependency version to >= 2.83.0

### ISSUE THREAD

**Issue by HowWeRollingham** [mapbox/node-pre-gyp#322]
Request 2.81.0 currently specified contains a [REDoS vulnerability](https://nodesecurity.io/advisories/525).

This is fixed as of version 2.83.0

**Comment by dancrumb** [comment]
PR #321 addresses this

**Comment by springmeyer** [comment]
Currently locked on older request due to https://github.com/mapbox/node-pre-gyp/pull/319. I will be releasing a newer node-pre-gyp series that drops node v0.10.x support in the coming weeks.

**Comment by christemple** [comment]
@springmeyer any updates on this?

**Comment by springmeyer** [comment]
@christemple thanks for the ping. Unfortunately no, but on my list. Will close this as soon as I have time to do a release.

**Comment by wtgtybhertgeghgtwtg** [comment]
If old versions will be dropped, maybe #245 could be back on the table.

**Comment by springmeyer** [comment]
@wtgtybhertgeghgtwtg - yes, that can be back on the table once I start a release series (1.x) that does not support node v0.x (v0.10.x or v0.12.x).

**Comment by springmeyer** [comment]
this is fixed in the v0.7.0 release that just landed.
