### ISSUE TITLE
Production should not include so many packages!

### ISSUE THREAD

**Issue by farfromrefug** [mapbox/node-pre-gyp#327]
if i had node-pre-gyp to my modules it has 30Mo!!!!
I am ok with that when i am building my app.
But that should not be the case in prod.
In prod the only thing you need from ```node-pre-gyp``` is ```find```
As an example i created a fork of ```node-pre-gyp``` which i called ```node-pre-gyp-prod```
Now in my native modules i put ```node-pre-gyp``` as a dev dependency and ``node-pre-gyp-prod``` as a dependency.
Also when i need to require my bindings i now use ```node-pre-gyp-prod```.
You can look at my fork of ```node-usb``` as an example.

This could and SHOULD be handled by ```node-pre-gyp```. You simply need to put all the dependencies as dev dependencies.
Please make that change for everyone to profit from this!

**Comment by springmeyer** [comment]
See #340
