### ISSUE TITLE
Thoughts on replacing 'request' library

### ISSUE THREAD

**Issue by cktang88** [mapbox/node-pre-gyp#340]
It seems the only place the `request` library is used is in `lib/install.js`, where it's only used for a simple task.
The `request` library is 52 packages, which take up around 4.22 MB, which seems unjustified for the small one-time usage that it gets included for. Would a PR be welcome to replace it with a lightweight alternative, such as [isomorphic-fetch](https://www.npmjs.com/package/isomorphic-fetch) or [simple-get](https://www.npmjs.com/package/simple-get) or something similar?

**Comment by LinusU** [comment]
ping @springmeyer 

Would love to see this happen! I would also be available to help whip up a PR if needed 👍

**Comment by dragonfire535** [comment]
Might I recommend [snekfetch](https://www.npmjs.com/package/snekfetch) too? No dependencies at all and very fast.

**Comment by springmeyer** [comment]
@cktang88 @LinusU @dragonfire535 - I would love to shrink the size of node-pre-gyp. I would welcome a PR that moves to something smaller, as long as the tests still pass.
