### ISSUE TITLE
Is "Pre-built binaries not found for ...." really an error?

### ISSUE THREAD

**Issue by davestephens** [mapbox/node-pre-gyp#344]
I guess this is more of a discussion point rather than a bug per-se, but please hear me out :-)

node-pre-gyp throws an error if it's requested to download a binary that doesn't exist for a specific platform. It then throws another error noting that it's falling back to compiling sources.

eg:
```
node-pre-gyp ERR! Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.13/node-v48-linux-arm.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for sqlite3@3.1.13 and node@6.12.3 (node-v48 ABI) (falling back to source compile with node-gyp) 
```
What the software is doing is expected, but it's not actually an "error" unless the compile fails - so misleading.

In my opinion the errors above should be logged as warnings, meaning that users not-so-familiar with Node.js don't get confused by messages in logs which can be safely ignored

Would appreciate thoughts on this!

Cheers
Dave

**Comment by springmeyer** [comment]
I agree. Would be happy to review a PR that changes this. I think you'd want to change the two `log.error` calls at https://github.com/mapbox/node-pre-gyp/blob/82b182b2483ce31fd13d5b2eee0b6e268206fd97/lib/install.js#L152-L153 to `log.warn`.

**Comment by agathver** [comment]
This confuses a lot of people using native modules. They report those two lines thinking that is the summary of installation breaking.

IMO, this should be a warning, as we have a fallback.
