### ISSUE TITLE
Staged files are being removed by MSBuild on Windows

### ISSUE THREAD

**Issue by pronebird** [mapbox/node-pre-gyp#351]
Hi,

I have a a build script that runs both on travis and appveyor to build node and electron binaries. However what I observe is that on Appveyor only the last staged file remains staged.

My package.json

```
"scripts": { 
  "install": "node-pre-gyp install --fallback-to-build",
  "package": "node-pre-gyp package",
  "test": "mocha"
},
```

That's my script for Appveyor:

```
  # build for nodejs
  - npm install --build-from-source
  - cmd: IF %APPVEYOR_REPO_TAG%==true npm run package --verbose

  - dir build\stage\0.0.3

  # build for electron
  - npm install --build-from-source --runtime=electron --target=%ELECTRON_VERSION% --dist-url=https://atom.io/download/atom-shell
  - cmd: IF %APPVEYOR_REPO_TAG%==true npm run package --runtime=electron --target=%ELECTRON_VERSION% --verbose

  - dir build\stage\0.0.3
```

So after building a node extension I get the following output:

```
dir build\stage\0.0.3
Volume in drive C is Windows
Volume Serial Number is D4AB-4044

Directory of C:\projects\windows-security\build\stage\0.0.3

03/12/2018  01:06 PM    <DIR>          .
03/12/2018  01:06 PM    <DIR>          ..
03/12/2018  01:06 PM           189,597 windows_security-v0.0.3-node-v57-win32-x64.tar.gz
               1 File(s)        189,597 bytes
               2 Dir(s)  47,268,945,920 bytes free
```

That looks fine. Now let's build the second file for electron and stage it too.

```
dir build\stage\0.0.3
Volume in drive C is Windows
Volume Serial Number is D4AB-4044

Directory of C:\projects\windows-security\build\stage\0.0.3

03/12/2018  01:06 PM    <DIR>          .
03/12/2018  01:06 PM    <DIR>          ..
03/12/2018  01:06 PM           189,621 windows_security-v0.0.3-electron-v1.8-win32-x64.tar.gz
               1 File(s)        189,621 bytes
               2 Dir(s)  47,241,920,512 bytes free
```

As you can see something erased the contents of staged directory after the first build.

**Comment by pronebird** [comment]
I figured that build tools on windows and mac behave different. My best bet is that MSBuild cleans up the build folder. It would probably make sense to stage files somewhere else to avoid that. I solved this by doing packaging after all build succeeded. Not sure if I should leave this issue open though.

**Comment by springmeyer** [comment]
> My best bet is that MSBuild cleans up the build folder. 

Which seems fine. The build folder may contain platform specific binaries, so cleaning it up makes sense.

> It would probably make sense to stage files somewhere else to avoid that. 

I don't feel this way. Rather the design of node-pre-gyp is such that you should publish right after you `package` such that the stage directory is only ephemeral.

> I solved this by doing packaging after all builds succeeded. Not sure if I should leave this issue open though.

Great, will close this then.
