### ISSUE TITLE
node-pre-gyp install --fallback-to-build changes my package.json

### ISSUE THREAD

**Issue by vktr** [mapbox/node-pre-gyp#353]
I've noticed that when I run `npm install --build-from-source` with `node-pre-gyp install --fallback-to-build` in my install script, my package.json file is changed from

```js
"napi_versions": [ 1 ]
```

to

```js
"napi_versions": [
  1
]
```

It's a small issue and I don't mind, but I'm reporting it for visibility :) Thanks for a great project!

**Comment by jschlight** [comment]
Thank you @vktr. In looking at this, I believe it's the `npm install` that's "improving" the package.json, not `node-pre-gyp`.

**Comment by vktr** [comment]
@jschlight Yeah, you are correct! Odd that I've never noticed this before 😄
