### ISSUE TITLE
Regression: binary installation does not follow redirects

### ISSUE THREAD

**Issue by allenluce** [mapbox/node-pre-gyp#359]
I've noticed this and had a user tell me about the same thing. When doing an `npm install mmap-object`:

```
> mmap-object@1.3.7 install /private/tmp/x/node_modules/mmap-object
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(302): https://github.com/allenluce/mmap-object/releases/download/1.3.7/mmap-object-v1.3.7-node-v48-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for mmap-object@1.3.7 and node@6.3.0 (node-v48 ABI, unknown) (falling back to source compile with node-gyp)
```
This is a new problem, I've only seen it within the last week or two.

**Comment by allenluce** [comment]
Looks like switching to needle (as part of #350) caused this. Needle doesn't follow redirects by default (as request does).

**Comment by allenluce** [comment]
This is pretty important as my module as it requires C++11 and Boost to be installed for compilation. That's [not always so straightforward for everyone](https://github.com/allenluce/mmap-object/issues/14).

**Comment by royaltm** [comment]
Yes, and currently using `node-pre-gyp-github` is impossible now, as github is redirecting it's release archives now to S3, e.g.:

`curl -D - https://github.com/royaltm/node-murmurhash-native/releases/download/v3.2.3/mu
rmurhash-v3.2.3-node-v46-linux-x64.tar.gz

HTTP/1.1 302 Found
Server: GitHub.com
Date: Thu, 29 Mar 2018 16:10:50 GMT
Content-Type: text/html; charset=utf-8
Transfer-Encoding: chunked
Status: 302 Found
(...)
Location: https://github-production-release-asset-2e65be.s3.amazonaws.com/(...)```

**Comment by springmeyer** [comment]
Fixed per https://github.com/mapbox/node-pre-gyp/pull/361#issuecomment-380947265. Thank you @allenluce

**Comment by allenluce** [comment]
Thanks for the merge!

**Comment by fireairforce** [comment]
So how to solve this question?
