### ISSUE TITLE
Redirects when downloading are not followed

### ISSUE THREAD

**Issue by pimterry** [mapbox/node-pre-gyp#360]
Redirects are not followed, resulting in errors like:

```
node-pre-gyp ERR! Tried to download(302): https://github.com/resin-io/node-ext2fs/releases/download/v1.0.1/bindings-v1.0.1-node-v57-linux-x64.tar.gz 
```

Here we're using https://www.npmjs.com/package/node-pre-gyp-github to store our release in github releases, and it appears there's been some github changes so this now results in a 302, which would take us to a successful download URL. 

Unfortunately that redirect which would be successful is not used (and the build fails instead), because node-pre-gyp only handles status code 200: https://github.com/mapbox/node-pre-gyp/blob/07e7ee57410c0887bf64b63676148364bbd90d47/lib/install.js#L108

**Comment by allenluce** [comment]
Check out #359 -- I ran into the same issue. I've submitted #361 to fix it.

**Comment by pimterry** [comment]
Awesome, thanks @allenluce! I'll close this then.
