### ISSUE TITLE
it builds from source twice when server hosting binaries responds with 403

### ISSUE THREAD

**Issue by x-yuri** [mapbox/node-pre-gyp#391]
[`install()`][1] function eventually calls [`place_binary()`][2]. The latter attaches both [`close`][3] and [`response`][4] event handlers to request. In case of 403 response, [`after_place()`][5] is called twice. As [is][6] [`do_build()`][7]. As such, we get two builds performed in parallel, which generally fail.

Steps to reproduce:
```
yarn add node-zopfli@2.0.2
```

[1]: https://github.com/mapbox/node-pre-gyp/blob/v0.10.0/lib/install.js#L159
[2]: https://github.com/mapbox/node-pre-gyp/blob/v0.10.0/lib/install.js#L204
[3]: https://github.com/mapbox/node-pre-gyp/blob/v0.10.0/lib/install.js#L102
[4]: https://github.com/mapbox/node-pre-gyp/blob/v0.10.0/lib/install.js#L108
[5]: https://github.com/mapbox/node-pre-gyp/blob/v0.10.0/lib/install.js#L208
[6]: https://github.com/mapbox/node-pre-gyp/blob/v0.10.0/lib/install.js#L211
[7]: https://github.com/mapbox/node-pre-gyp/blob/v0.10.0/lib/install.js#L129

**Comment by kevinmehall** [comment]
It seems this can also occur on a 404. For example https://gitlab.com/drom/jtag/-/jobs/80286481:
```
node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp WARN Tried to download(404): https://github.com/tessel/node-usb/releases/download/1.3.2/usb_bindings-v1.3.2-node-v64-linux-x64.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for usb@1.3.2 and node@10.6.0 (node-v64 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Pre-built binaries not installable for usb@1.3.2 and node@10.6.0 (node-v64 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error Connection closed while downloading tarball file 
make: Entering directory '/builds/drom/jtag/node_modules/usb/build'
  CC(target) Release/obj.target/libusb/libusb/libusb/core.o
make: Entering directory '/builds/drom/jtag/node_modules/usb/build'
  CC(target) Release/obj.target/libusb/libusb/libusb/core.o
```

**Comment by kevinmehall** [comment]
This might be related to https://github.com/nodejs/node/issues/21063 (I've only seen this happen on Node 10)

**Comment by pumano** [comment]
I got the same scenario. I have `usb` and `serialport`. Building from source via `electron-builder` got race condition for file access. It starts after upgrading from node 10.1 to 10.6. Currently as workaround I downgrade `nodejs` to 10.1 and it compile successfully. Looks like it can be caused by nodejs/node#21063 

stacktrace:
```
 win_delay_load_hook.cc
C:\Users\myuser\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\src\win_delay_load_hook.cc : fatal error C
1083: Cannot open include file: C:\Repository\MyApp\node_modules\usb\build\Release\ob
j\libusb\win_delay_load_hook.obj: Permission denied [C:\Repository\MyApp\node_modules\usb\build\libusb.vc
xproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\myuser\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
```
