### ISSUE TITLE
Node.js 4 and 5 support dropped but no major version update?

### ISSUE THREAD

**Issue by BHare1985** [mapbox/node-pre-gyp#407]
I saw that 0.10.0 dropped Node.js 4 and 5 support ( https://github.com/mapbox/node-pre-gyp/commit/4d88e052da37a71afa3407da1fccf340fe93148a )

According to semver, this would be a breaking change (IMO) and should of warranted a major version update.

If you do decide to make previous versions node.js 4/5 friendly, then you have to consider that node-tar should be linked to version 4.4.0 (or even lower) because since node-pre-gyp 0.7.0  the package.json has had `tar: ^4` but they have said that v4 and v5 hasnt  been supported in years, which includes their version 4 releases.

The cause for this suggestion is the grief experienced from https://github.com/mapbox/node-pre-gyp/issues/406

**Comment by springmeyer** [comment]
Sorry about the breakage. I tried hard to keep 0.10 working: https://github.com/mapbox/node-pre-gyp/pull/319 but it was a loosing battle given the decision at https://github.com/request/request/issues/2772 to bring in deps that broken 0.10.x support without a major bump. Is it possible for you to downgrade to `node-pre-gyp@0.6.37` if you still need v0.10.x support?

**Comment by BHare1985** [comment]
Yes I can overcome this issue personally. I was just speaking on behalf of others who may not be so fortunate.

Also, I am not concerned about node v0.10.x support. I think any v0.x support is reasonable to drop at this point. I was referring to node-pre-gyp 0.10.0 dropped node v4.x and node v5.x. 
The last node v4 change was in 2018-03-29 but stopped being maintained april 2018 ( https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V4.md )

**Comment by mapsam** [comment]
@BHare1985 just a note about semver - major version 0 allows for breaking changes anywhere in the release cycle. [source](https://semver.org/#spec-item-4)

> Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

I'm not saying this is great, but technically semver allows for these types of changes to occur without a major bump. That said, at some point node-pre-gyp 1.x discussions should probably happen!

**Comment by nicolasnoble** [comment]
Yeah, it's true that semver technically allows this, but many people in the nodejs world expect that a 0-major would like to identify breaking changes through a minor version bump.

Citation from https://docs.npmjs.com/misc/semver about caret dependencies:

> Allows changes that do not modify the left-most non-zero digit in the `[major, minor, patch]` tuple. In other words, this allows patch and minor updates for versions `1.0.0` and above, patch updates for versions `0.X >=0.1.0`, and _no_ updates for versions `0.0.X`.
> Many authors treat a `0.x` version as if the `x` were the major "breaking-change" indicator.
> Caret ranges are ideal when an author may make breaking changes between `0.2.4` and `0.3.0` releases, which is a common practice. However, it presumes that there will _not_ be breaking changes between `0.2.4` and `0.2.5`. It allows for changes that are presumed to be additive (but non-breaking), according to commonly observed practices.

**Comment by BHare1985** [comment]
Yes I forgot about the 0.X exceptions. There were numerous node modules that I contacted in regards to node-tar dropping v4 and v5 support. node-tar made the breaking change on their end within version 4 major.  Many other node modules have their  versioning at > 0.X yet reference 0.X modules so it's frustrating.

I am making the switch to node v6 and hopefully going to take advantage of package-lock to avoid issues in the future.

I believe based on the semver definition that node-pre-gyp is justified in making a breaking change within their 0.x version and will close this issue

**Comment by mapsam** [comment]
Right on @BHare1985 - I feel you on the upgrade pain. Good luck on the switch!
