### ISSUE TITLE
Differences between runtimes

### ISSUE THREAD

**Issue by jonathan-roy** [mapbox/node-pre-gyp#437]
Hi,

I'm new to Node addons and I wonder what is the difference between, for example, `node-pre-gyp rebuild --runtime=node --target 10.11.0` and `node-pre-gyp rebuild --runtime=electron --version=4.0.0`.

Since Electron 4.0.0 embeds Node 10.11.0, isn't this the same?

**Comment by nicolasnoble** [comment]
Not at all. The electron binary contains nodejs code, but the dependencies are different, and they do not expose the same overall API. Depending on the actual thing you're native module does, it might be possible to create a single binary that matches both runtimes, but it's much safer to always treat them as distinct.

**Comment by jonathan-roy** [comment]
Actually my module is a wrapper around a shared library, allowing to call the library functions from JavaScript. It is written with Node Addon Api (which itself relies on N-API), and this module will be used in an Electron application.

So, in order to compile this module correctly I should:
* set the `binary.napi_versions` property to `[3]` in my `package.json`.
* define `NAPI_VERSION`in `binding.gyp`.
*  compile with `node-pre-gyp --runtime=electron --target=4.0.0 `

Is this correct?

**Comment by nicolasnoble** [comment]
So, if you're limiting yourself strictly to the n-API, your add-on might work properly without having to recompile it for each runtime. I haven't tested it myself however.

Otherwise, yes, your command line is correct.

**Comment by jonathan-roy** [comment]
Ok I see, thank you for your explanation!
