### ISSUE TITLE
Might it be time to release node 11.X support to npm?

### ISSUE THREAD

**Issue by tlbtlbtlb** [mapbox/node-pre-gyp#438]
The 0.12 release from October doesn't support node 11, which makes it hard to distribute code.

**Comment by nicolasnoble** [comment]
Except it should.

https://github.com/mapbox/node-pre-gyp/pull/422

Can you elaborate on the issue?

**Comment by tlbtlbtlb** [comment]
My mistake, I had an old version installed globally.
