### ISSUE TITLE
node-pre-gyp WARN Using needle for node-pre-gyp https download 

### ISSUE THREAD

**Issue by masumbillah** [mapbox/node-pre-gyp#439]
Any idea. Why this error?

node-pre-gyp WARN Using needle for node-pre-gyp https download 
node-pre-gyp WARN Pre-built binaries not installable for fsevents@1.2.7 and node@10.15.1 (node-v64 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error EACCES: permission denied, mkdir '/usr/local/lib/node_modules/nodemon/node_modules/fsevents/lib' 
gyp WARN EACCES user "root" does not have permission to access the dev dir "/Users/ms/.node-gyp/10.15.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/nodemon/node_modules/fsevents/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/nodemon/node_modules/fsevents/.node-gyp'
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/usr/local/lib/node_modules/nodemon/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node" "--module_name=fse" "--module_path=/usr/local/lib/node_modules/nodemon/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64" "--napi_version=3" "--node_abi_napi=napi"
gyp ERR! cwd /usr/local/lib/node_modules/nodemon/node_modules/fsevents
gyp ERR! node -v v10.15.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/local/lib/node_modules/nodemon/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node --module_name=fse --module_path=/usr/local/lib/node_modules/nodemon/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64 --napi_version=3 --node_abi_napi=napi' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/nodemon/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:970:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
node-pre-gyp ERR! System Darwin 17.7.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/nodemon/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/local/lib/node_modules/nodemon/node_modules/fsevents
node-pre-gyp ERR! node -v v10.15.1
node-pre-gyp ERR! node-pre-gyp -v v0.10.3
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/local/lib/node_modules/nodemon/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node --module_name=fse --module_path=/usr/local/lib/node_modules/nodemon/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64 --napi_version=3 --node_abi_napi=napi' (1)

> nodemon@1.18.10 postinstall /usr/local/lib/node_modules/nodemon
> node bin/postinstall || exit 0

Love nodemon? You can now support the project via the open collective:
 > https://opencollective.com/nodemon/donate

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/nodemon/node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 install: `node install`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

**Comment by nicolasnoble** [comment]
You're mixing up a warning and an error that have nothing in common from this log. The actual error is you don't have write permissions to the destination folder. If you are running as root, try adding `--unsafe-perm`

**Comment by mikemaccana** [comment]
For anyone else here who is getting the warning:

> node-pre-gyp WARN Using needle for node-pre-gyp https download

What does needle mean and why is it bad?

**Comment by rantebi** [comment]
I had the same issue on my mac, I noticed at the end of the warnings and errors there a line saying:
`You have not agreed to the Xcode license agreements, please run 'xcodebuild -license' (for user-level acceptance) or 'sudo xcodebuild -license' (for system-wide acceptance) from within a Terminal window to review and agree to the Xcode license agreements.`

So I ran `sudo xcodebuild -license`, agreed to the terms, then re-ran `ng new` and it was OK.

**Comment by Lanskask** [comment]
Thanks for advice, but doesn't work for me

**Comment by kalovatvatey** [comment]
It might have something to do with the stable node release and dependency. I was getting this error with bycrpt dependency.

**Comment by river133** [comment]
C:\Users\river\front_end\grpc_demo> npm install -g grpc-tools
npm ERR! code EEXIST
npm ERR! path C:\Users\river\AppData\Roaming\npm\node_modules\grpc-tools\bin\protoc_plugin.js
 
我也出现了这样的报错，有大佬帮忙吗？

**Comment by Shahed34** [comment]
"node-pre-gyp WARN Using request for node-pre-gyp https download"
When a project run my machine ,i am installing "npm install" but #warn msg show above the line .how ca i solve this problem?
Thanks

**Comment by Eunknight** [comment]
canvas & other solution
https://github.com/mapbox/node-pre-gyp/issues/526#issue-753211483

**Comment by CodenameCookie** [comment]
Any updates to this? When it tries via "needle" it always fails for me.

**Comment by nicejs-is-cool** [comment]
i have a similar warning to this one but im trying to install node-gtk and im using a ARM device with linux
(Raspberry Pi 4 B)

**Comment by springmeyer** [comment]
This warning is now fixed in the @mapbox/node-pre-gyp@1.0.0 release. The fix is from #551: we've added support (which should work with http proxies) that uses node-fetch.
