### ISSUE TITLE
High severity vulnerability found in tar

### ISSUE THREAD

**Issue by kaiwen-zhang-ck** [mapbox/node-pre-gyp#446]
Using Synk, I found security vulnerability in the package tar. I am using from package React Scripts. Please see Synk screenshots
![Screen Shot 2019-04-10 at 9 55 58 AM](https://user-images.githubusercontent.com/46582740/55898366-477b2780-5b77-11e9-8c95-156661caa5f7.png)

You can see details about this vulnerability here
[https://snyk.io/vuln/SNYK-JS-TAR-174125](url)

![Screen Shot 2019-04-10 at 10 00 30 AM](https://user-images.githubusercontent.com/46582740/55898465-827d5b00-5b77-11e9-9ae4-4ab54919b3bd.png)

Solution is to upgrade tar version

**Comment by nicolasnoble** [comment]
Feel free to send a PR. Note that the current package.json is using a caret dependency on version 4, so it ought to pick up version 4.4.2 on its own if you don't pin the package version yourself.

**Comment by kaiwen-zhang-ck** [comment]
That is interesting. I dont think it is pinned. But when i do `npm i` i see these warnings. Somehow the new version is not picked up 

<img width="838" alt="Screen Shot 2019-04-10 at 10 28 45 AM" src="https://user-images.githubusercontent.com/46582740/55900171-72677a80-5b7b-11e9-8bef-6483fb66efeb.png">

**Comment by nicolasnoble** [comment]
Check if you don't have a package-lock.json file?

**Comment by kaiwen-zhang-ck** [comment]
yep, i have package-lock.json file. I am not sure if this warning is related to not installing the latest tar

**Comment by kaiwen-zhang-ck** [comment]
I see that the latest tar 4.4.8 but my version installed is `tar@4.4.1`

**Comment by nicolasnoble** [comment]
So if you have a package-lock.json file, it's basically pinning versions to whichever versions you first installed. Try removing the file and reinstalling.

**Comment by kaiwen-zhang-ck** [comment]
here is what i did
```
rm package-lock.json
rm -rf node-modules
npm i
```
still installed tar@4.4.1 sigh....

**Comment by kaiwen-zhang-ck** [comment]
![Screen Shot 2019-04-10 at 11 43 30 AM](https://user-images.githubusercontent.com/46582740/55905012-f4f53780-5b85-11e9-9eb5-4274dad97957.png)

**Comment by kaiwen-zhang-ck** [comment]
could this be an issue with fsevents?

**Comment by murgatroid99** [comment]
The issue is probably that node-pre-gyp is a bundled dependency, so it and all of its sub-dependencies are locked to specific versions. And yes, fsevents would need to update their dependencies to fix this.

**Comment by nicolasnoble** [comment]
Right, yes. You're not a node-pre-gyp user yourself, I realize. You are using node-pre-gyp transitively. Yes, this is an issue with react-scripts in this case, that depends on an older version of fsevents, which in turns pins dependencies. Please file this with react-scripts instead.

**Comment by kaiwen-zhang-ck** [comment]
i manage to resolve this issue by manually going into `package-lock.json` and search for `"tar"`. find the the `"tar"` that is incorrect version and change it to 

```
"tar": {
              "version": "4.4.8",
              "bundled": true,
              "optional": true,
              "requires": {
                "chownr": "^1.1.1",
                "fs-minipass": "^1.2.5",
                "minipass": "^2.3.4",
                "minizlib": "^1.1.1",
                "mkdirp": "^0.5.0",
                "safe-buffer": "^5.1.2",
                "yallist": "^3.0.2"
              }
            }
```

seemed to resolve this issue. thanks for the help!
