### ISSUE TITLE
A per-dependency "build-from-source" option?

### ISSUE THREAD

**Issue by danielgindi** [mapbox/node-pre-gyp#448]
Is there a way to do something like
`npm config set sqlite-build-from-source` in order to trigger build only for the dependency named "sqlite"?

**Comment by nicolasnoble** [comment]
Yes. `npm rebuild --build-from-source=sqlite3`

**Comment by danielgindi** [comment]
Thank you!

But is it possible to do this as a config value?
So npm install does not have to be called explicitly with cli args each time

**Comment by ikokostya** [comment]
I have the same issue. It can be done by adding `build-from-source = true` setting to `.npmrc` in the project root:

```
build-from-source = true
```

See node-gyp documentation https://github.com/nodejs/node-gyp#environment-variables

@nicolasnoble Maybe describe this is documentation?
