### ISSUE TITLE
Module not found: Can't resolve 'aws-sdk'

### ISSUE THREAD

**Issue by woodyjon** [mapbox/node-pre-gyp#457]
Hello,

I am using a module that uses node-pre-gyp (node-rfc). When I launch my app, it says
```
Failed to compile.

./node_modules/node-rfc/node_modules/node-pre-gyp/lib/info.js
Module not found: Can't resolve 'aws-sdk' in '***/app/node_modules/node-rfc/node_modules/node-pre-gyp/lib'
```

(the module uses "node-pre-gyp": "^0.12.0")

I do not understand where does that come from. Maybe you can help.

Thank you!

**Comment by nicolasnoble** [comment]
`aws-sdk` is a development dependency of `node-pre-gyp`, and can be used to push build artifacts to AWS. The fact you got this error means you (1) somehow triggered the unpublishing step (which you probably couldn't do if you're not an author of `node-rfc`) and (2) you don't have the development modules installed. While (2) is reasonable, (1) is the part where something's wrong. You shouldn't have triggered that codepath that is.

That being said, you're mentioning that the module uses `node-pre-gyp` version `^0.12.0`, but according to the sources, that's not true:

https://github.com/SAP/node-rfc/blob/master/package.json#L12

Maybe it'd be reasonable to open an issue on `node-rfc` instead.

**Comment by woodyjon** [comment]
OK thank you! I will check with node-rfc.
I use a more recent branch of node-rfc, indeed with `^0.12.0`: https://github.com/SAP/node-rfc/blob/napi/package.json

Thanks!
