### ISSUE TITLE
node-pre-gyp install --fallback-to-build

### ISSUE THREAD

**Issue by ekam230** [mapbox/node-pre-gyp#478]
ERROR: Error:  { [Error: Request DependencyInstaller/install failed with message: 
> sqlite3@4.0.8 install /home/ekam230/.vscode/extensions/mtxr.sqltools-0.21.0/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp ERR! Completion callback never invoked! 
node-pre-gyp ERR! System Linux 5.0.0-27-generic
node-pre-gyp ERR! command "/home/ekam230/.nvm/versions/node/v12.7.0/bin/node" "/home/ekam230/.vscode/extensions/mtxr.sqltools-0.21.0/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/ekam230/.vscode/extensions/mtxr.sqltools-0.21.0/node_modules/sqlite3
node-pre-gyp ERR! node -v v12.7.0
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! This is a bug in `node-pre-gyp`.
node-pre-gyp ERR! Try to update node-pre-gyp and file an issue if it does not help:
node-pre-gyp ERR!     <https://github.com/mapbox/node-pre-gyp/issues>
npm ERR! code ELIFECYCLE
npm ERR! errno 6
npm ERR! sqlite3@4.0.8 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 6
npm ERR! 
npm ERR! Failed at the sqlite3@4.0.8 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ekam230/.npm/_logs/2019-09-24T07_17_25_471Z-debug.log

	at /home/ekam230/.vscode/extensions/mtxr.sqltools-0.21.0/extension.js:1:22985
	at /home/ekam230/.vscode/extensions/mtxr.sqltools-0.21.0/extension.js:1:23392
	at Immediate.module.exports.messageQueue.size.setImmediate (/home/ekam230/.vscode/extensions/mtxr.sqltools-0.21.0/extension.js:1:23936)
	at runCallback (timers.js:694:18)
	at tryOnImmediate (timers.js:665:5)
	at processImmediate (timers.js:647:5)] code: -32603, data: undefined }
INFO: Executing SQLTools.showOutputChannel

**Comment by SamLebarbare** [comment]
Alone in the dark... :dark_sunglasses:

**Comment by froblesmartin** [comment]
Duplicated. Just the previous issue is the same: https://github.com/mapbox/node-pre-gyp/issues/477

**Comment by springmeyer** [comment]
see https://github.com/mapbox/node-pre-gyp/issues/477#issuecomment-534630617
