### ISSUE TITLE
Installation failing on node <=6 due to minizlib@1.3.x

### ISSUE THREAD

**Issue by elssar** [mapbox/node-pre-gyp#481]
`minilib` v1.3.0 introduced a change which is not compatible in node 6 and lower.

The offending [line](https://github.com/isaacs/minizlib/blob/v1.3.0/constants.js#L2) -
```
const { ZLIB_VERNUM } = require('zlib').constants
```

Ref: https://github.com/isaacs/minizlib/issues/9

**Comment by himanshusinghs** [comment]
Explicitly installing `minizlib` v1.2.2 worked for us.

**Comment by elssar** [comment]
Fixed now.
