### ISSUE TITLE
rc dependency - out of date

### ISSUE THREAD

**Issue by redevill** [mapbox/node-pre-gyp#493]
It appears that you have yet another security problem with a lib called rc. This library(rc) is out of date (refers to minimist which has had a security update), and does not appear to be maintained. recommend that you removed this (rc) dependency...

**Comment by jt-nti** [comment]
There is an rc PR to update the version of minimist dominictarr/rc#114 but not sure how likely it is to get merged

**Comment by redevill** [comment]
I did see that, but after no action on that lib for 3 years, I figured it would be faster to incorporate the code into your library and remove the dependency. It is quite surprising how far reaching the minimist vulnerability is... I have over 300 npm warnings in my project as a result. Thanks for the reply.

**Comment by springmeyer** [comment]
This is fixed in @mapbox/node-pre-gyp@1.0.0 which no longer uses `rc` dependency.

**Comment by redevill** [comment]
Cool Beans :)
