### ISSUE TITLE
please remove mkdirp or update it to 1.0.x!

### ISSUE THREAD

**Issue by keel** [mapbox/node-pre-gyp#495]
the npm will show vulnerabilities after install node-pre-gyp

**Comment by felixhao28** [comment]
Additionally, mkdirp@0.5.3 has a syntax error in one of its scripts, and this causes tools like WebPack to fail.

https://github.com/substack/node-mkdirp/blob/f2003bbcffa80f8c9744579fabab1212fc84545a/bin/cmd.js#L13

**Comment by springmeyer** [comment]
solved in e67acfa6f4f4cb3b0241286b53d2564c3c56c1fe (and the upcoming v1.x release of node-pre-gyp)
