### ISSUE TITLE
[Feature request] allow forcing node-pre-gyp to always use prebuilt binary

### ISSUE THREAD

**Issue by grahamjenson** [mapbox/node-pre-gyp#508]
Some environments need to always use specific build settings, e.g. gRPC with ALPN off https://github.com/grpc/grpc/issues/18549. Rebuilding is very expensive so ensuring that a user is using the correct binary is important. This could be accomplished in the `.npmrc` file, e.g.:

```
grpc_node_binary_host_mirror=https://bucket.s3.amazonaws.com
grpc_never_build=true
```

This would specifically turn off the `fallback-to-build` option that is in the `install` script in the grpc package.

**Comment by springmeyer** [comment]
You can do `npm install --fallback-to-build=false` to override what might be in the install script. So I'm pretty sure what you are asking for is already supported. Please re-open a new issue if you find it is not.
