### ISSUE TITLE
Outstanding Security Vulnerability via RC which is using an out of date INI version

### ISSUE THREAD

**Issue by martin-fogelman** [mapbox/node-pre-gyp#535]
Hi Folks,

Node-pre-gyp uses RC, which in turn is using an out of date ini version with a high severity prototype pollution vulnerability: https://app.snyk.io/vuln/SNYK-JS-INI-1048974

It looks like RC hasn't been updated in some time and it's already been a few weeks (granted there were holidays), so I'm escalating the issue here in case folks can help. See [RC issue 120](https://github.com/dominictarr/rc/issues/120) and RC [resolved but unmerged PR 121](https://github.com/dominictarr/rc/pull/121).

A quick review does seem to show that Dominic was responsive in the past re minimist? (See [RC pull 114](https://github.com/dominictarr/rc/pull/114) and [RC pull 115](https://github.com/dominictarr/rc/pull/115); cf. #493)

Thanks

**Comment by springmeyer** [comment]
I think node-pre-gyp can likely get away without using RC in a future release. So I may just go that direction: https://github.com/mapbox/node-pre-gyp/tree/remove-rc

**Comment by jmz527** [comment]
@springmeyer just checking in, any updates on this?

**Comment by springmeyer** [comment]
Yes, node-pre-gyp upcoming v1.0.0 release will drop rc (#552) so this issue will be resolved

**Comment by motishani** [comment]
@springmeyer do you know when the new v1.0.0 will be released?

**Comment by springmeyer** [comment]
@motishani an alpha is already available. Try doing:

```
npm install @mapbox/node-pre-gyp@1.0.0-alpha4 --save
```

**Comment by springmeyer** [comment]
@mapbox/node-pre-gyp@1.0.0 is now released, which solves this.
