### ISSUE TITLE
error while installing firebase

### ISSUE THREAD

**Issue by Sahilamin219** [mapbox/node-pre-gyp#541]
`node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.6.32
node-pre-gyp info using node@8.10.0 | linux | x64
node-pre-gyp info build requesting source compile
gyp info it worked if it ends with ok
gyp info using node-gyp@3.2.1
gyp info using node@8.10.0 | linux | x64
gyp info ok 
node-pre-gyp ERR! UNCAUGHT EXCEPTION 
node-pre-gyp ERR! stack Error: expressdawa package.json is not node-pre-gyp ready:
node-pre-gyp ERR! stack package.json must declare these properties: 
node-pre-gyp ERR! stack binary.module_name
node-pre-gyp ERR! stack binary.module_path
node-pre-gyp ERR! stack binary.host
node-pre-gyp ERR! stack     at validate_config (/usr/lib/nodejs/node-pre-gyp/lib/util/versioning.js:203:15)
node-pre-gyp ERR! stack     at Object.module.exports.evaluate (/usr/lib/nodejs/node-pre-gyp/lib/util/versioning.js:261:5)
node-pre-gyp ERR! stack     at handle_gyp_opts (/usr/lib/nodejs/node-pre-gyp/lib/util/handle_gyp_opts.js:54:27)
node-pre-gyp ERR! stack     at configure (/usr/lib/nodejs/node-pre-gyp/lib/configure.js:11:5)
node-pre-gyp ERR! stack     at /usr/lib/nodejs/node-pre-gyp/lib/build.js:35:13
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/lib/nodejs/node-pre-gyp/lib/util/compile.js:85:9)
node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
node-pre-gyp ERR! System Linux 4.18.0-20-generic
node-pre-gyp ERR! command "/usr/bin/node" "/usr/bin/node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
node-pre-gyp ERR! cwd /home/sahil/Downloads/expressdawa
node-pre-gyp ERR! node -v v8.10.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.32
node-pre-gyp ERR! This is a bug in `node-pre-gyp`.
node-pre-gyp ERR! Try to update node-pre-gyp and file an issue if it does not help:
node-pre-gyp ERR!     <https://github.com/mapbox/node-pre-gyp/issues>
`
i got an error while running npm install --save firebase which basically said to run and install this
node-pre-gyp install --fallback-to-build --library=static_library
which further gave the above error .

**Comment by springmeyer** [comment]
report this to the firebase author
