### ISSUE TITLE
update to remove request

### ISSUE THREAD

**Issue by bmacnaughton** [mapbox/node-pre-gyp#546]
@springmeyer - if you're interested, i'll work on a quick update to replace request with axios or alternatively node-fetch.

request is deprecated so a new release shouldn't go out with it.

i'd use axios by default; i'm not familiar with node-fetch. but it is about 1/2 the size of axios and, at this point, is getting enough downloads that it's not a wonky alternative. axios has 1 dependency; node-fetch has 0, so it seems like a good alternative.

https://www.npmtrends.com/axios-vs-node-fetch-vs-request

**Comment by springmeyer** [comment]
Thanks for raising this. I wonder if we can get away with just needle. The reason request is still used is that needle, when integrated, did not work with proxies (https://github.com/mapbox/node-pre-gyp/issues/400). Perhaps https://github.com/mapbox/node-pre-gyp/pull/511 would address that, if landed. Then we'd be able to just use needle. Alternatively I've seen node core devs working on https://github.com/nodejs/undici which looks interesting. Thoughts?

**Comment by bmacnaughton** [comment]
considering the very limited scope of use for the module, it seems like smaller should be a major factor, given that it works. either needle or node-fetch are the best choices based on that criteria. undici and axios have quite a few features node-pre-gyp neither needs nor uses but either would be a viable solution.

- node-fetch is 158 KB with 0 dependencies; 16821 dependents, 19M downloads/week
- needle is 217 KB with 3 dependencies: debug (4 KB), iconv-lite (344 KB), sax (really big). 787 dependents, 5M downloads/week

so node-fetch seems the best choice from that standpoint of size and usage metrics.

the main benefit i see to needle is that it's already being used.

both node-fetch and needle require an agent to to be passed in to handle a proxy, so your #511 would be pretty close to what's required in either case.

i'd opt for using node-fetch.

there are a few proxy server solutions that could become part of testing; i haven't done anything more than find them, but they look like they could help with testing.

**Comment by springmeyer** [comment]
Thanks for the additional thoughts. I'm 👍 on the optimization criteria: a) what node-pre-gyp needs (HTTP simple Gets + proxy support + good error handling) and b) size (since node-pre-gyp is used by dependencies that try to stay light).

So, it does sound like node-fetch addresses those well and therefore I'd approve a PR that switches to node-fetch assuming that it has tests of proxy support + some documented effort at manual testing to confirm it works.

**Comment by springmeyer** [comment]
landed in #551 thanks @bmacnaughton!
