### ISSUE TITLE
Problem with this

### ISSUE THREAD

**Issue by TheBigBoy-TheBitcoin** [mapbox/node-pre-gyp#568]
IDK what this is for i need it to install discordjs/opus, but it doesn't work

C:\Users\Francesco>node-pre-gyp install --fallback-to-build
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.17.0
node-pre-gyp info using node@14.15.5 | win32 | x64
node-pre-gyp WARN Using needle for node-pre-gyp https download
node-pre-gyp info build requesting source compile
gyp info it worked if it ends with ok
gyp info using node-gyp@7.1.2
gyp info using node@14.15.5 | win32 | x64
gyp info ok
node-pre-gyp ERR! UNCAUGHT EXCEPTION
node-pre-gyp ERR! stack Error: undefined package.json is not node-pre-gyp ready:
node-pre-gyp ERR! stack package.json must declare these properties:
node-pre-gyp ERR! stack main
node-pre-gyp ERR! stack version
node-pre-gyp ERR! stack name
node-pre-gyp ERR! stack binary.module_name
node-pre-gyp ERR! stack binary.module_path
node-pre-gyp ERR! stack binary.host
node-pre-gyp ERR! stack     at validate_config (C:\Users\Francesco\AppData\Roaming\npm\node_modules\node-pre-gyp\lib\util\versioning.js:220:15)
node-pre-gyp ERR! stack     at Object.module.exports.evaluate (C:\Users\Francesco\AppData\Roaming\npm\node_modules\node-pre-gyp\lib\util\versioning.js:279:5)
node-pre-gyp ERR! stack     at handle_gyp_opts (C:\Users\Francesco\AppData\Roaming\npm\node_modules\node-pre-gyp\lib\util\handle_gyp_opts.js:60:27)
node-pre-gyp ERR! stack     at configure (C:\Users\Francesco\AppData\Roaming\npm\node_modules\node-pre-gyp\lib\configure.js:12:5)
node-pre-gyp ERR! stack     at C:\Users\Francesco\AppData\Roaming\npm\node_modules\node-pre-gyp\lib\build.js:43:13
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\Francesco\AppData\Roaming\npm\node_modules\node-pre-gyp\lib\util\compile.js:85:9)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1048:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
node-pre-gyp ERR! System Windows_NT 10.0.19041
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Francesco\\AppData\\Roaming\\npm\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\Francesco
node-pre-gyp ERR! node -v v14.15.5
node-pre-gyp ERR! node-pre-gyp -v v0.17.0
node-pre-gyp ERR! This is a bug in `node-pre-gyp`.
node-pre-gyp ERR! Try to update node-pre-gyp and file an issue if it does not help:
node-pre-gyp ERR!     <https://github.com/mapbox/node-pre-gyp/issues>

**Comment by springmeyer** [comment]
It looks like you are running `node-pre-gyp install` directly. That is not the right way to use it. Rather it is integrated into a node C++ addon that needs node-pre-gyp for packaging its binaries. If you are confused or having trouble installing `discordjs/opus` then you should bring that up with `discordjs/opus`
