### ISSUE TITLE
CANNOT INSTALL OPUS HELP 

### ISSUE THREAD

**Issue by TheBigBoy-TheBitcoin** [mapbox/node-pre-gyp#569]
PS C:\Users\Francesco\Desktop\Siti & Bots\NoyzStream BOT Discord> npm i @discordjs/opus
npm ERR! code 1
npm ERR! path C:\Users\Francesco\Desktop\Siti & Bots\NoyzStream BOT Discord\node_modules\@discordjs\opus
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node-pre-gyp install --fallback-to-build
npm ERR! Impossibile trovare il percorso specificato.
npm ERR! node:internal/modules/cjs/loader:926
npm ERR!   throw err;
npm ERR!   ^
npm ERR!
npm ERR! Error: Cannot find module 'C:\Users\Francesco\Desktop\@discordjs\node-pre-gyp\bin\node-pre-gyp'
npm ERR!     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:923:15)
npm ERR!     at Function.Module._load (node:internal/modules/cjs/loader:768:27)
npm ERR!     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
npm ERR!     at node:internal/main/run_main_module:17:47 {
npm ERR!   code: 'MODULE_NOT_FOUND',
npm ERR!   requireStack: []
npm ERR! }

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Francesco\AppData\Local\npm-cache\_logs\2021-02-24T14_21_23_825Z-debug.log
PS C:\Users\Francesco\Desktop\Siti & Bots\NoyzStream BOT Discord>

**Comment by springmeyer** [comment]
Discord is using a forked version of node-pre-gyp so this is not the right place to create an issue: https://github.com/discordjs/opus/blob/master/package.json#L29. Rather https://github.com/discordjs/opus/issues/70 is correct/enough.
