### ISSUE TITLE
node-pre-gyp ERR! UNCAUGHT EXCEPTION

### ISSUE THREAD

**Issue by M4r5ha11** [mapbox/node-pre-gyp#578]
path C:\Users\m4r5h\Downloads\server-testing\node_modules\sqlite3
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node-pre-gyp install --fallback-to-build
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@0.6.2
npm ERR! node-pre-gyp info using node@15.8.0 | win32 | x64
npm ERR! node-pre-gyp info check checked for "C:\Users\m4r5h\Downloads\server-testing\node_modules\sqlite3\lib\binding\node-v88-win32-x64\node_sqlite3.node" (not found)
npm ERR! node-pre-gyp http GET https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.0.5/node-v88-win32-x64.tar.gz
npm ERR! node-pre-gyp ERR! UNCAUGHT EXCEPTION
npm ERR! node-pre-gyp ERR! stack **ReferenceError: primordials is not defined**
npm ERR! node-pre-gyp ERR! stack     at evalmachine.<anonymous>:51:5
npm ERR! node-pre-gyp ERR! stack     at Object.<anonymous> (C:\Users\m4r5ha11\Downloads\server-testing\node_modules\sqlite3\node_modules\node-pre-gyp\node_modules\tar\node_modules\fstream\node_modules\graceful-fs\fs.js:11:1)
npm ERR! node-pre-gyp ERR! stack     at Module._compile (node:internal/modules/cjs/loader:1108:14)
npm ERR! node-pre-gyp ERR! stack     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
npm ERR! node-pre-gyp ERR! stack     at Module.load (node:internal/modules/cjs/loader:973:32)
npm ERR! node-pre-gyp ERR! stack     at Function.Module._load (node:internal/modules/cjs/loader:813:14)
npm ERR! node-pre-gyp ERR! stack     at Module.require (node:internal/modules/cjs/loader:997:19)
npm ERR! node-pre-gyp ERR! stack     at require (node:internal/modules/cjs/helpers:92:18)
npm ERR! node-pre-gyp ERR! stack     at Object.<anonymous> (C:\Users\m4r5ha11\Downloads\server-testing\node_modules\sqlite3\node_modules\node-pre-gyp\node_modules\tar\node_modules\fstream\node_modules\graceful-fs\graceful-fs.js:3:27)
npm ERR! node-pre-gyp ERR! stack     at Module._compile (node:internal/modules/cjs/loader:1108:14)
npm ERR! node-pre-gyp ERR! System Windows_NT 10.0.19042
npm ERR! node-pre-gyp ERR! command "B:\\Program Files\\nodejs\\node.exe" "C:\\Users\\m4r5ha11\\Downloads\\server-testing\\node_modules\\sqlite3\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
npm ERR! node-pre-gyp ERR! cwd C:\Users\m4r5h11\Downloads\server-testing\node_modules\sqlite3
npm ERR! node-pre-gyp ERR! node -v v15.8.0
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v0.6.2
npm ERR! node-pre-gyp ERR! This is a bug in `node-pre-gyp`.
npm ERR! node-pre-gyp ERR! Try to update node-pre-gyp and file an issue if it does not help:
npm ERR! node-pre-gyp ERR!     <https://github.com/mapbox/node-pre-gyp/issues>

**Comment by springmeyer** [comment]
Hmm, interesting issue. This looks like a breakage between dependencies of node-pre-gyp and your node version: https://stackoverflow.com/questions/55921442/how-to-fix-referenceerror-primordials-is-not-defined-in-node

**Comment by springmeyer** [comment]
If you downgrade to node v12 or v14 does the problem persist or go away?
