### ISSUE TITLE
package.json  --build-from-source for all dependencies

### ISSUE THREAD

**Issue by kapouer** [mapbox/node-pre-gyp#58]
Is there a way, in a package.json, to tell all dependencies (using node-pre-gyp) to build from source ? That could happen when one doesn't want prebuilt binaries of the dependencies at all.

**Comment by moll** [comment]
Stumbled upon the same issue 4 years later and was surprised I've already commented here. :P Why is this issue still closed? After all, it _is_ still the default search engine result as it perfectly describes what we, security conscious people, all want.
