### ISSUE TITLE
Your shit is broken

### ISSUE THREAD

**Issue by ozdeadmeat** [mapbox/node-pre-gyp#598]
`0 verbose cli [
0 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
0 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
0 verbose cli   'i',
0 verbose cli   '--unsafe-perm',
0 verbose cli   'node-red-contrib-queued-sqlite'
0 verbose cli ]
1 info using npm@7.11.2
2 info using node@v16.1.0
3 timing npm:load:whichnode Completed in 1ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:C:\Program Files\nodejs\node_modules\npm\npmrc Completed in 2ms
6 timing config:load:builtin Completed in 2ms
7 timing config:load:cli Completed in 2ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:G:\GameServer\DDC2\.npmrc Completed in 0ms
10 timing config:load:project Completed in 1ms
11 timing config:load:file:C:\Users\c0rnerst0ne\.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:C:\Users\c0rnerst0ne\AppData\Roaming\npm\etc\npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:credentials Completed in 0ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 8ms
19 timing npm:load:configload Completed in 8ms
20 timing npm:load:setTitle Completed in 0ms
21 timing npm:load:setupLog Completed in 2ms
22 timing npm:load:cleanupLog Completed in 2ms
23 timing npm:load:configScope Completed in 0ms
24 timing npm:load:projectScope Completed in 0ms
25 timing npm:load Completed in 15ms
26 timing config:load:flatten Completed in 2ms
27 timing arborist:ctor Completed in 6ms
28 timing idealTree:init Completed in 72ms
29 timing idealTree:userRequests Completed in 1ms
30 silly idealTree buildDeps
31 silly fetch manifest node-red-contrib-queued-sqlite@*
32 verbose shrinkwrap failed to load node_modules/.package-lock.json out of date, updated: node_modules
33 http fetch GET 304 https://registry.npmjs.org/node-red-contrib-queued-sqlite 832ms (from cache)
34 silly placeDep ROOT node-red-contrib-queued-sqlite@0.0.4 OK for:  want: *
35 silly fetch manifest sqlite3@^4.0.4
36 http fetch GET 304 https://registry.npmjs.org/sqlite3 42ms (from cache)
37 timing idealTree:#root Completed in 882ms
38 silly placeDep ROOT sqlite3@4.2.0 OK for: node-red-contrib-queued-sqlite@0.0.4 want: ^4.0.4
39 silly fetch manifest nan@^2.12.1
40 silly fetch manifest node-pre-gyp@^0.11.0
41 http fetch GET 304 https://registry.npmjs.org/nan 47ms (from cache)
42 http fetch GET 304 https://registry.npmjs.org/node-pre-gyp 85ms (from cache)
43 timing idealTree:node_modules/node-red-contrib-queued-sqlite Completed in 91ms
44 silly placeDep ROOT nan@2.15.0 OK for: sqlite3@4.2.0 want: ^2.12.1
45 silly placeDep node_modules/sqlite3 node-pre-gyp@0.11.0 OK for: sqlite3@4.2.0 want: ^0.11.0
46 silly fetch manifest mkdirp@^0.5.1
47 silly fetch manifest nopt@^4.0.1
48 silly fetch manifest rimraf@^2.6.1
49 silly fetch manifest semver@^5.3.0
50 silly fetch manifest tar@^4
51 http fetch GET 304 https://registry.npmjs.org/semver 50ms (from cache)
52 http fetch GET 304 https://registry.npmjs.org/mkdirp 54ms (from cache)
53 http fetch GET 304 https://registry.npmjs.org/rimraf 73ms (from cache)
54 http fetch GET 304 https://registry.npmjs.org/tar 79ms (from cache)
55 http fetch GET 304 https://registry.npmjs.org/nopt 85ms (from cache)
56 timing idealTree:node_modules/sqlite3 Completed in 91ms
57 timing idealTree:node_modules/nan Completed in 0ms
58 silly placeDep node_modules/sqlite3 mkdirp@0.5.5 OK for: node-pre-gyp@0.11.0 want: ^0.5.1
59 silly placeDep node_modules/sqlite3 nopt@4.0.3 OK for: node-pre-gyp@0.11.0 want: ^4.0.1
60 silly placeDep node_modules/sqlite3 rimraf@2.7.1 OK for: node-pre-gyp@0.11.0 want: ^2.6.1
61 silly placeDep node_modules/sqlite3 semver@5.7.1 OK for: node-pre-gyp@0.11.0 want: ^5.3.0
62 silly placeDep node_modules/sqlite3 tar@4.4.15 OK for: node-pre-gyp@0.11.0 want: ^4
63 silly fetch manifest chownr@^1.1.1
64 silly fetch manifest fs-minipass@^1.2.5
65 silly fetch manifest minipass@^2.8.6
66 silly fetch manifest minizlib@^1.2.1
67 silly fetch manifest yallist@^3.0.3
68 http fetch GET 304 https://registry.npmjs.org/chownr 44ms (from cache)
69 http fetch GET 304 https://registry.npmjs.org/minipass 54ms (from cache)
70 http fetch GET 304 https://registry.npmjs.org/fs-minipass 58ms (from cache)
71 http fetch GET 304 https://registry.npmjs.org/yallist 59ms (from cache)
72 http fetch GET 304 https://registry.npmjs.org/minizlib 63ms (from cache)
73 timing idealTree:node_modules/sqlite3/node_modules/node-pre-gyp Completed in 72ms
74 timing idealTree:node_modules/sqlite3/node_modules/mkdirp Completed in 0ms
75 timing idealTree:node_modules/sqlite3/node_modules/nopt Completed in 0ms
76 timing idealTree:node_modules/sqlite3/node_modules/rimraf Completed in 0ms
77 timing idealTree:node_modules/sqlite3/node_modules/semver Completed in 0ms
78 silly placeDep node_modules/sqlite3 chownr@1.1.4 OK for: tar@4.4.15 want: ^1.1.1
79 silly placeDep node_modules/sqlite3 fs-minipass@1.2.7 OK for: tar@4.4.15 want: ^1.2.5
80 silly placeDep node_modules/sqlite3 minipass@2.9.0 OK for: tar@4.4.15 want: ^2.8.6
81 silly placeDep node_modules/sqlite3 minizlib@1.3.3 OK for: tar@4.4.15 want: ^1.2.1
82 silly placeDep node_modules/sqlite3 yallist@3.1.1 OK for: tar@4.4.15 want: ^3.0.3
83 timing idealTree:node_modules/sqlite3/node_modules/tar Completed in 4ms
84 timing idealTree:node_modules/sqlite3/node_modules/chownr Completed in 0ms
85 timing idealTree:node_modules/sqlite3/node_modules/fs-minipass Completed in 0ms
86 timing idealTree:node_modules/sqlite3/node_modules/minipass Completed in 0ms
87 timing idealTree:node_modules/sqlite3/node_modules/minizlib Completed in 0ms
88 timing idealTree:node_modules/sqlite3/node_modules/yallist Completed in 0ms
89 timing idealTree:buildDeps Completed in 1144ms
90 timing idealTree:fixDepFlags Completed in 1ms
91 timing idealTree Completed in 1220ms
92 timing reify:loadTrees Completed in 1220ms
93 timing reify:diffTrees Completed in 6ms
94 silly reify moves {}
95 timing reify:retireShallow Completed in 0ms
96 timing reify:createSparse Completed in 4ms
97 timing reify:loadBundles Completed in 0ms
98 timing reifyNode:node_modules/sqlite3/node_modules/fs-minipass Completed in 111ms
99 timing reifyNode:node_modules/sqlite3/node_modules/chownr Completed in 111ms
100 timing reifyNode:node_modules/sqlite3/node_modules/minipass Completed in 124ms
101 timing reifyNode:node_modules/sqlite3/node_modules/minizlib Completed in 125ms
102 timing reifyNode:node_modules/sqlite3/node_modules/yallist Completed in 128ms
103 timing reifyNode:node_modules/sqlite3/node_modules/rimraf Completed in 128ms
104 timing reifyNode:node_modules/sqlite3/node_modules/mkdirp Completed in 133ms
105 timing reifyNode:node_modules/sqlite3/node_modules/nopt Completed in 140ms
106 timing reifyNode:node_modules/sqlite3/node_modules/semver Completed in 143ms
107 timing reifyNode:node_modules/node-red-contrib-queued-sqlite Completed in 145ms
108 timing reifyNode:node_modules/sqlite3/node_modules/tar Completed in 209ms
109 warn deprecated node-pre-gyp@0.11.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
110 timing reifyNode:node_modules/sqlite3/node_modules/node-pre-gyp Completed in 221ms
111 http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/advisories/bulk 245ms
112 timing auditReport:getReport Completed in 247ms
113 timing auditReport:init Completed in 0ms
114 timing reify:audit Completed in 249ms
115 timing reifyNode:node_modules/nan Completed in 261ms
116 timing reifyNode:node_modules/sqlite3 Completed in 313ms
117 timing reify:unpack Completed in 313ms
118 timing reify:unretire Completed in 0ms
119 timing build:queue Completed in 1ms
120 timing build:link:node_modules/sqlite3/node_modules/mkdirp Completed in 26ms
121 timing build:link:node_modules/sqlite3/node_modules/node-pre-gyp Completed in 26ms
122 timing build:link:node_modules/sqlite3/node_modules/nopt Completed in 25ms
123 timing build:link:node_modules/sqlite3/node_modules/rimraf Completed in 25ms
124 timing build:link:node_modules/sqlite3/node_modules/semver Completed in 25ms
125 timing build:link Completed in 27ms
126 info run sqlite3@4.2.0 install node_modules/sqlite3 node-pre-gyp install --fallback-to-build
127 info run sqlite3@4.2.0 install { code: 1, signal: null }
128 timing reify:rollback:createSparse Completed in 58ms
129 timing reify:rollback:retireShallow Completed in 0ms
130 timing command:install Completed in 3541ms
131 verbose stack Error: command failed
131 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\promise-spawn\index.js:64:27)
131 verbose stack     at ChildProcess.emit (node:events:365:28)
131 verbose stack     at maybeClose (node:internal/child_process:1067:16)
131 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
132 verbose pkgid sqlite3@4.2.0
133 verbose cwd G:\GameServer\DDC2
134 verbose Windows_NT 10.0.19042
135 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "--unsafe-perm" "node-red-contrib-queued-sqlite"
136 verbose node v16.1.0
137 verbose npm  v7.11.2
138 error code 1
139 error path G:\GameServer\DDC2\node_modules\sqlite3
140 error command failed
141 error command C:\Windows\system32\cmd.exe /d /s /c node-pre-gyp install --fallback-to-build
142 error Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=G:\GameServer\DDC2\node_modules\sqlite3\lib\binding\node-v93-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=G:\GameServer\DDC2\node_modules\sqlite3\lib\binding\node-v93-win32-x64 --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93' (1)
143 error node-pre-gyp info it worked if it ends with ok
143 error node-pre-gyp info using node-pre-gyp@0.11.0
143 error node-pre-gyp info using node@16.1.0 | win32 | x64
143 error node-pre-gyp WARN Using needle for node-pre-gyp https download
143 error node-pre-gyp info check checked for "G:\GameServer\DDC2\node_modules\sqlite3\lib\binding\node-v93-win32-x64\node_sqlite3.node" (not found)
143 error node-pre-gyp http GET https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.2.0/node-v93-win32-x64.tar.gz
143 error node-pre-gyp http 403 https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.2.0/node-v93-win32-x64.tar.gz
143 error node-pre-gyp WARN Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.2.0/node-v93-win32-x64.tar.gz
143 error node-pre-gyp WARN Pre-built binaries not found for sqlite3@4.2.0 and node@16.1.0 (node-v93 ABI, unknown) (falling back to source compile with node-gyp)
143 error node-pre-gyp http 403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.2.0/node-v93-win32-x64.tar.gz
143 error gyp info it worked if it ends with ok
143 error gyp info using node-gyp@7.1.2
143 error gyp info using node@16.1.0 | win32 | x64
143 error gyp info ok
143 error gyp info it worked if it ends with ok
143 error gyp info using node-gyp@7.1.2
143 error gyp info using node@16.1.0 | win32 | x64
143 error gyp ERR! find Python
143 error gyp ERR! find Python Python is not set from command line or npm configuration
143 error gyp ERR! find Python Python is not set from environment variable PYTHON
143 error gyp ERR! find Python checking if "python3" can be used
143 error gyp ERR! find Python - "python3" is not in PATH or produced an error
143 error gyp ERR! find Python checking if "python" can be used
143 error gyp ERR! find Python - "python" is not in PATH or produced an error
143 error gyp ERR! find Python checking if "python2" can be used
143 error gyp ERR! find Python - "python2" is not in PATH or produced an error
143 error gyp ERR! find Python checking if Python is C:\Python37\python.exe
143 error gyp ERR! find Python - "C:\Python37\python.exe" could not be run
143 error gyp ERR! find Python checking if Python is C:\Python27\python.exe
143 error gyp ERR! find Python - "C:\Python27\python.exe" could not be run
143 error gyp ERR! find Python checking if the py launcher can be used to find Python
143 error gyp ERR! find Python - "py.exe" is not in PATH or produced an error
143 error gyp ERR! find Python
143 error gyp ERR! find Python **********************************************************
143 error gyp ERR! find Python You need to install the latest version of Python.
143 error gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
143 error gyp ERR! find Python you can try one of the following options:
143 error gyp ERR! find Python - Use the switch --python="C:\Path\To\python.exe"
143 error gyp ERR! find Python   (accepted by both node-gyp and npm)
143 error gyp ERR! find Python - Set the environment variable PYTHON
143 error gyp ERR! find Python - Set the npm configuration variable python:
143 error gyp ERR! find Python   npm config set python "C:\Path\To\python.exe"
143 error gyp ERR! find Python For more information consult the documentation at:
143 error gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
143 error gyp ERR! find Python **********************************************************
143 error gyp ERR! find Python
143 error gyp ERR! configure error
143 error gyp ERR! stack Error: Could not find any Python installation to use
143 error gyp ERR! stack     at PythonFinder.fail (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-python.js:302:47)
143 error gyp ERR! stack     at PythonFinder.runChecks (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-python.js:136:21)
143 error gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-python.js:200:18)
143 error gyp ERR! stack     at PythonFinder.execFileCallback (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-python.js:266:16)
143 error gyp ERR! stack     at exithandler (node:child_process:333:5)
143 error gyp ERR! stack     at ChildProcess.errorhandler (node:child_process:345:5)
143 error gyp ERR! stack     at ChildProcess.emit (node:events:365:28)
143 error gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:288:12)
143 error gyp ERR! stack     at onErrorNT (node:internal/child_process:480:16)
143 error gyp ERR! stack     at processTicksAndRejections (node:internal/process/task_queues:83:21)
143 error gyp ERR! System Windows_NT 10.0.19042
143 error gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=G:\\GameServer\\DDC2\\node_modules\\sqlite3\\lib\\binding\\node-v93-win32-x64\\node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=G:\\GameServer\\DDC2\\node_modules\\sqlite3\\lib\\binding\\node-v93-win32-x64" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v93"
143 error gyp ERR! cwd G:\GameServer\DDC2\node_modules\sqlite3
143 error gyp ERR! node -v v16.1.0
143 error gyp ERR! node-gyp -v v7.1.2
143 error gyp ERR! not ok
143 error node-pre-gyp ERR! build error
143 error node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=G:\GameServer\DDC2\node_modules\sqlite3\lib\binding\node-v93-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=G:\GameServer\DDC2\node_modules\sqlite3\lib\binding\node-v93-win32-x64 --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93' (1)
143 error node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (G:\GameServer\DDC2\node_modules\sqlite3\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
143 error node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:365:28)
143 error node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1067:16)
143 error node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
143 error node-pre-gyp ERR! System Windows_NT 10.0.19042
143 error node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "G:\\GameServer\\DDC2\\node_modules\\sqlite3\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
143 error node-pre-gyp ERR! cwd G:\GameServer\DDC2\node_modules\sqlite3
143 error node-pre-gyp ERR! node -v v16.1.0
143 error node-pre-gyp ERR! node-pre-gyp -v v0.11.0
143 error node-pre-gyp ERR! not ok
144 verbose exit 1
`

**Comment by watsoncj** [comment]
This is not a problem with node-pre-gyp. The error states that Python was not found on the system.

`Error: Could not find any Python installation to use`

**Comment by dbrgn** [comment]
ozdeadmeat: Your sense of entitlement is broken.
