### ISSUE TITLE
all the package need node-pre-gyp take err when install

### ISSUE THREAD

**Issue by flameleo11** [mapbox/node-pre-gyp#617]
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! libxmljs@0.18.8 install: `node-pre-gyp install --fallback-to-build --loglevel http`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the libxmljs@0.18.8 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by springmeyer** [comment]
Please file an issue with the libxmljs developers. This is unrelated to node-pre-gyp.
