### ISSUE TITLE
Vulnerable dependency - Canvas

### ISSUE THREAD

**Issue by guillaumearnx** [mapbox/node-pre-gyp#620]
Hello, someone tells me to open an issue here

[Original link](https://github.com/Automattic/node-canvas/issues/1916)

I have an issue with `node canvas` and one of the collaborators replied that the problem could come from here

![](https://user-images.githubusercontent.com/37373941/139508642-a7f3be0d-a757-4310-91fa-707453340910.png)
 
Thank's

**Comment by springmeyer** [comment]
Thanks for the heads up. I tried to create a dependabot PR for this, but it looks to be blocked on npmlog:

https://github.com/npm/npmlog/issues/85.

![Screen Shot 2021-11-15 at 12 20 58 PM](https://user-images.githubusercontent.com/20300/141848399-973ea659-2ddc-41a3-a04a-9ec3b11affe4.png)

**Comment by fredkilbourn** [comment]
@springmeyer this is actually coming from way upstream but the fix is making its way down.  npmlog has a PR open right now that will update to gauge 4.0 which fixes this: https://github.com/npm/npmlog/pull/84

Keep an eye on it and we'll have a fix you can pull in soon.

**Comment by fredkilbourn** [comment]
@springmeyer npmlog v6 just published, should address the issue

**Comment by springmeyer** [comment]
Thanks. @mapbox/node-pre-gyp@1.0.7 is now published which includes npmlog@6
