### ISSUE TITLE
Programmatically specify the architecture, since wrong one used when called from Ruby

### ISSUE THREAD

**Issue by garyking** [mapbox/node-pre-gyp#664]
Per my issue here: https://github.com/TryGhost/node-sqlite3/issues/1627 when I run a Node script, which uses `node-sqlite3` which uses `node-pre-gyp`, through Ruby, it uses the wrong architecture. If the script is run through Node only, then it works fine.

In Ruby, I have the following code:

```
`/usr/local/bin/node "script.js"`
```

With the backticks, it runs the code and returns the output.

With the above code, I get the following error:

```
node:internal/modules/cjs/loader:949
  throw err;
  ^

Error: Cannot find module 'node_modules/sqlite3/lib/binding/napi-v6-darwin-unknown-x64/node_sqlite3.node'
Require stack:
- node_modules/sqlite3/lib/sqlite3-binding.js
- node_modules/sqlite3/lib/sqlite3.js
- script.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:946:15)
    at Module._load (node:internal/modules/cjs/loader:787:27)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (node_modules/sqlite3/lib/sqlite3-binding.js:4:17)
    at Module._compile (node:internal/modules/cjs/loader:1112:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1166:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:834:12)
    at Module.require (node:internal/modules/cjs/loader:1012:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'node_modules/sqlite3/lib/sqlite3-binding.js',
    'node_modules/sqlite3/lib/sqlite3.js',
    'script.js',
  ]
}

Node.js v18.5.0
```

The error presumably occurs because it should be looking for `napi-v6-darwin-unknown-arm64` rather than `napi-v6-darwin-unknown-x64` since I'm on an Apple M1 chip.

Is there a way I can explicitly specify the architecture to use when I run the Node script through Ruby?

**Comment by garyking** [comment]
I managed to fix the issue by changing this:

```ruby
`/usr/local/bin/node "script.js"`
```

To this:

```ruby
`arch -arm64 /usr/local/bin/node "script.js"`
```

**Comment by springmeyer** [comment]
@garyking I think your assumption is likely correct: that the missing module is due to a different arch being used between the install vs runtime. You should be able to confirm this by looking inside the `node_modules/sqlite3/lib/binding/` folder to see if an `arm64` based binary is present and not an `x64` binary.


> Is there a way I can explicitly specify the architecture to use when I run the Node script through Ruby?

I think based on the way Macs + node work you could either do:

`arch --x86_64 /usr/local/bin/node "script.js"`

or you could downgrade node to a version before node provided arm64 binaries. (I think that node v14 would do it).

**Comment by springmeyer** [comment]
Ha, looks like you figured it out 21 seconds before I pressed go on my comment. Glad you resolved it.
