### ISSUE TITLE
Overriding "host" to point to alternative binary repository

### ISSUE THREAD

**Issue by springmeyer** [mapbox/node-pre-gyp#74]
Logging this idea. Not positive its a good idea and I may not move on it, but...

Say you want to [support much older linux distros](https://github.com/mapnik/node-mapnik/issues/228) with custom binaries. As a developer of an app that depends on node-pre-gyp packaged modules you might want to keep 99% of what node-pre-gyp provides but just request that binaries be fetched from an alternative endpoint that you maintain. If we were to support this then an `npm config` style override might be possible:

``` sh
npm config set node-pre-gyp_mapnik_host https://node-mapnik-alternative.s3-us-west-1.amazonaws.com
```

Then instead of `https://node-mapnik.s3-us-west-1.amazonaws.com` being used from https://github.com/mapnik/node-mapnik/blob/c36d90b237e76e013bcd2c2e15d11ad304658a9a/package.json#L13, the alternative `host` would be used:

```
npm install mapnik
node-pre-gyp http GET https://node-mapnik-alternative.s3-us-west-1.amazonaws.com/v1.4.2/mapnik-v1.4.2-node-v11-darwin-x64.tar.gz
```

**Comment by fmarmar** [comment]
This should be a must. This morning our entire ci system was down because we couldn't download or build a binary needed by a transitive dependency.

**Comment by springmeyer** [comment]
@fmarmar I think this may be supported after https://github.com/mapbox/node-pre-gyp/pull/459

However the breakage this morning impacted everyone using node-tar, so not just node-pre-gyp. And an alliterative repository would not have helped since the breakage was do to the inability to unpack the tar: https://github.com/mapbox/node-pre-gyp/issues/477#issuecomment-534630617
