### ISSUE TITLE
Deprecated dependencies in @mapbox/node-pre-gyp

### ISSUE THREAD

**Issue by leeobrum** [mapbox/node-pre-gyp#882]
`-- @mapbox/node-pre-gyp@1.0.11
         `-- npmlog@5.0.1
npm warn deprecated npmlog@5.0.1: This package is no longer supported.

`-- @mapbox/node-pre-gyp@1.0.11
        `-- rimraf@3.0.2
npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported.

`-- @mapbox/node-pre-gyp@1.0.11
        `-- rimraf@3.0.2
          `-- glob@7.2.3
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported.

 `-- @mapbox/node-pre-gyp@1.0.11
        `-- npmlog@5.0.1
          `-- are-we-there-yet@2.0.0
npm warn deprecated are-we-there-yet@2.0.0: This package is no longer supported.

`-- @mapbox/node-pre-gyp@1.0.11
        `-- npmlog@5.0.1
          `-- gauge@3.0.2
npm warn deprecated gauge@3.0.2: This package is no longer supported.

**Comment by cclauss** [comment]
What is the status of this?

**Comment by leeobrum** [comment]
![image](https://github.com/user-attachments/assets/c83e27c5-c229-4e0e-8012-80deb1c92a67)

I think the projects migrated from the node-pre-gyp@1.0.11 library, as I am no longer being warned about these libraries.
